<?php
echo $this->headtitle("Forgot Password"); ?>

<section id="forgotPassword" class="h-screen flex items-center justify-center relative overflow-hidden bg-[url('../../assets/images/hero/bg3.jpg')] bg-no-repeat bg-left-bottom bg-cover">
    <div class="absolute inset-0 bg-gradient-to-b from-transparent to-black"></div>
    <div class="container">
        <div class="grid lg:grid-cols-3 md:grid-cols-2 grid-cols-1">
            <div class="relative overflow-hidden bg-white dark:bg-slate-900 shadow-md dark:shadow-gray-800 rounded-md">
                <div class="p-6">
                    <a href="">
                        <img src="assets/images/logo-dark.png" class="mx-auto h-[24px] block dark:hidden" alt="">
                        <img src="assets/images/logo-light.png" class="mx-auto h-[24px] dark:block hidden" alt="">
                    </a>
                    <h5 class="my-6 text-xl font-semibold">Reset Your Password</h5>
                    <div class="grid grid-cols-1">
                        <p class="text-slate-400 mb-6">Please enter your email address. You will receive a link to create a new password via email.</p>

                        <div class="grid grid-cols-1">
                            <div class="mb-4 ltr:text-left rtl:text-right">
                                <label class="font-semibold" for="LoginEmail">Email Address: <span style="font-size: x-small; color : red;">*</span></label>
                                <input v-model="email" @input="validateEmail()" id="LoginEmail" type="email" class="form-input mt-3 rounded-md" placeholder="name@example.com">
                                <span class="floating-placeholder" style="font-size: x-small; color : red;" v-if="msg.email">{{msg.email}}</span>
                            </div>

                            <div class="mb-4">
                                <div v-if="isSubmitting">
                                    <i class="fas fa-spinner fs-3x"></i>
                                </div>
                                <button v-else @click="reset()" class="btn bg-emerald-600 hover:bg-emerald-700 border-emerald-600 hover:border-emerald-700 text-white rounded-md w-full">Send</button>
                            </div>

                            <div class="text-center">
                                <span class="text-slate-400 me-2">Remember your password ? </span><a href="<?= $this->url("login") ?>" class="text-black dark:text-white font-bold">Sign in</a>
                            </div>
                        </div>

                    </div>
                </div>


            </div>
        </div>
    </div>
</section><!--end section -->

<script>
    const forgotPassword = Vue.createApp({
        data() {
            return {
                email: "",
                msg: {
                    email: "",
                    isInvalidEmail: true,
                }
            }
        },

        methods: {
            validateForm() {
                if (!this.msg.isInvalidEmail) {
                    this.isValid = true;

                } else {
                    this.isValid = false;

                }
            },


            validateEmail() {


                if (!(/^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$/.test(this.email))) {
                    this.msg.email = 'Please enter a valid email address';
                    this.msg.isInvalidEmail = true;

                } else {
                    this.msg.email = '';
                    this.msg.isInvalidEmail = false;

                }
                this.validateForm()
            },

            reset() {
                this.isSubmitting = true;
                if (this.email == "") {
                    Swal.fire({
                        icon: "error",
                        title: "Empty field",
                        text: "Email Field is empty"
                    })
                } else {
                    let formData = new FormData();
                    formData.append("email", this.email);
                    axios.post("/auth/forgot-password", formData).then((result) => {
                        if (result.status == 201) {
                            Swal.fire({
                                icon: "success",
                                title: "Reset Link sent",
                                test: "A reset link has been sent to you email"
                            });
                            this.isSubmitting = false;
                        }
                    }).catch((err) => {

                    });
                }

            }
        },
    });
    forgotPassword.use(VueToast.ToastPlugin);
    forgotPassword.mount("#forgotPassword");
</script>