<?php

use Application\Service\ApplicationService;
use General\Service\GeneralService;

?>
<?= $this->doctype() ?>
<html lang="en">

<head>
    <meta charset="utf-8">
    <?= $this->headTitle(GeneralService::APP_NAME)->setSeparator(' - ')->setAutoEscape(false) ?>

    <!-- Font Awesome Icons -->
    <script src="https://kit.fontawesome.com/42d5adcbca.js" crossorigin="anonymous"></script>
    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?= $this->headLink([
        'rel' => 'shortcut icon',
        'type' => 'image/vnd.microsoft.icon',
        'href' => $this->basePath() . '/img/favicon.ico'
    ])


        ->prependStylesheet($this->basePath("assets/css/tailwind.css"))
        ->prependStylesheet($this->basePath("assets/libs/@mdi/font/css/materialdesignicons.min.css"))
        ->prependStylesheet($this->basePath("assets/libs/@iconscout/unicons/css/line.css"))


    ?>

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" />

    <!-- Font Awesome Link -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css" integrity="sha512-HK5fgLBL+xu6dm/Ii3z4xhlSUyZgTT9tuc/hSrtw6uzJOvgRr2a9jyxxT1ely+B+xFAmJKVSTbpM/CuL7qxO8w==" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://unpkg.com/@material-tailwind/html@latest/styles/material-tailwind.css" />

    <!-- script -->
    <script src="https://unpkg.com/@material-tailwind/html@latest/scripts/script-name.js"></script>

    <script src="https://unpkg.com/@material-tailwind/html@latest/scripts/ripple.js"></script>

    <script src="https://unpkg.com/vue@3/dist/vue.global.js"></script>
    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

    <script src="https://cdn.jsdelivr.net/npm/vue-toast-notification@3"></script>
    <link href="https://cdn.jsdelivr.net/npm/vue-toast-notification@3/dist/theme-sugar.css" rel="stylesheet">

    <!-- Scripts -->
    <?= $this->headScript() ?>
</head>

<body class="dark:bg-slate-900">
    <!-- Loader Start -->
    <!-- <div id="preloader">
            <div id="status">
                <div class="spinner">
                    <div class="double-bounce1"></div>
                    <div class="double-bounce2"></div>
                </div>
            </div>
        </div> -->
    <!-- Loader End -->

    <?php
    $flashMessenger = $this->flashMessenger()
        ->setMessageOpenFormat('<div%s  role="alert">
               
             
     <ul><li>')

        ->setMessageCloseString('</div>');
    ?>
    <?php echo $flashMessenger->render('error', ['p-4 mb-4', 'text-sm text-red-800', 'rounded-lg', 'bg-red-50', 'dark:bg-gray-800', 'dark:text-red-400']); ?>
    <?php echo $flashMessenger->render('info', ['alert', 'p-4 mb-4', 'text-sm text-blue-800', 'rounded-lg', 'bg-blue-50', 'dark:bg-gray-800', 'dark:text-blue-400']); ?>
    <?php echo $flashMessenger->render('default', ['alert', 'p-4 mb-4', 'text-sm text-yellow-800', 'rounded-lg', 'bg-yellow-50', 'dark:bg-gray-800', 'dark:text-yellow-400']); ?>
    <?php echo $flashMessenger->render('success', ['alert', 'p-4 mb-4', 'text-sm text-green-800', 'rounded-lg', 'bg-green-50', 'dark:bg-gray-800', 'dark:text-green-400']); ?>


    <?= $this->content ?>




    <!-- JAVASCRIPTS -->
    <script src="/assets/libs/feather-icons/feather.min.js"></script>
    <script src="/assets/js/plugins.init.js"></script>
    <script src="/assets/js/app.js"></script>
    <!-- JAVASCRIPTS -->
</body>



</html>