<?php


foreach ($this->container as $key => $page) :
    /** @var Laminas\Navigation\Page\AbstractPage $page */

    ?>
    <li class="nav-item">
        <a data-bs-toggle="collapse" href="#pagesExamples_<?= $key ?>" class="nav-link " aria-controls="pagesExamples_<?= $key ?>" role="button" aria-expanded="false">
            <div class="icon icon-shape icon-sm shadow border-radius-md bg-white text-center d-flex align-items-center justify-content-center  me-2">
                <svg width="12px" height="12px" viewBox="0 0 42 42" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
                    <title>office</title>
                    <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                        <g transform="translate(-1869.000000, -293.000000)" fill="#FFFFFF" fill-rule="nonzero">
                            <g transform="translate(1716.000000, 291.000000)">
                                <g id="office" transform="translate(153.000000, 2.000000)">
                                    <path class="color-background" d="M12.25,17.5 L8.75,17.5 L8.75,1.75 C8.75,0.78225 9.53225,0 10.5,0 L31.5,0 C32.46775,0 33.25,0.78225 33.25,1.75 L33.25,12.25 L29.75,12.25 L29.75,3.5 L12.25,3.5 L12.25,17.5 Z" opacity="0.6"></path>
                                    <path class="color-background" d="M40.25,14 L24.5,14 C23.53225,14 22.75,14.78225 22.75,15.75 L22.75,38.5 L19.25,38.5 L19.25,22.75 C19.25,21.78225 18.46775,21 17.5,21 L1.75,21 C0.78225,21 0,21.78225 0,22.75 L0,40.25 C0,41.21775 0.78225,42 1.75,42 L40.25,42 C41.21775,42 42,41.21775 42,40.25 L42,15.75 C42,14.78225 41.21775,14 40.25,14 Z M12.25,36.75 L7,36.75 L7,33.25 L12.25,33.25 L12.25,36.75 Z M12.25,29.75 L7,29.75 L7,26.25 L12.25,26.25 L12.25,29.75 Z M35,36.75 L29.75,36.75 L29.75,33.25 L35,33.25 L35,36.75 Z M35,29.75 L29.75,29.75 L29.75,26.25 L35,26.25 L35,29.75 Z M35,22.75 L29.75,22.75 L29.75,19.25 L35,19.25 L35,22.75 Z"></path>
                                </g>
                            </g>
                        </g>
                    </g>
                </svg>
            </div>
            <span class="nav-link-text ms-1"><?php //echo $page->getLabel() ?></span>
        </a>
        <div class="collapse " id="pagesExamples_<?= $key ?>">
            <?php if ($page->hasPages()) : ?>
                <ul class="nav ms-4 ps-3">


                    <?php

                    foreach ($page->getPages() as $child) :
                        ?>

                        <li class="nav-item ">
                            <a class="nav-link " href="<?php echo $child->getHref() ?>">
                                <span class="sidenav-mini-icon"> P </span>
                                <span class="sidenav-normal"> <?php echo $child->getLabel() ?></span>
                            </a>
                        </li>
                    <?php endforeach ?>

                </ul>
            <?php endif; ?>
        </div>
    </li>
<?php endforeach; ?>