<div class="row">
    <div class="col-md-6">
        <div class="form-group form-control-material">
            <input type="text" class="form-control" id="jobTitle" ref="jobTitle" placeholder="Job Title e.g Web Developer">
          <!--  <label for="jobTitle">Title of Job</label> -->
        </div>
    </div>
    <div class="col-md-6">
        <div class="form-group form-control-material">
            <input type="email" class="form-control" id="exampleInputLastName" placeholder="Your last name">
            <label for="exampleInputLastName">Last name</label>
        </div>
    </div>
</div>
<div class="form-group form-control-material static required">
    <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Enter email">
    <label for="exampleInputEmail1">Email address</label>
</div>

<br>