<div class="row">
    <div class="col-md-6">
        <h4>Job Description</h4>
        <div class="form-group form-control-material">
            <quill-editor ref="myee" rows="5" contentType="html" theme="snow"></quill-editor>
        </div>
    </div>
    <div class="col-md-6">
        <div class="form-group form-control-material">
            <input type="email" class="form-control" id="exampleInputLastName" placeholder="Your last name">
            <label for="exampleInputLastName">Last name</label>
        </div>
    </div>
</div>
<div class="form-group form-control-material static required">
    <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Enter email">
    <label for="exampleInputEmail1">Email address</label>
</div>
<div class="form-group  static required">

    <hr>
</div>
<br>