<?php

use General\Service\GeneralService;
?>
<div class="row">
    <div class="col-md-6">
        <label>Application Medium</label>
        <div v-for="link in jobApplyLink" class="radio radio-primary">
            <input @change="clickedApplyLink" v-model="selectedApplyLink" type="radio" name="applyLink" :id="link.id" :value="link.id">
            <label :for="link.id">{{link.applyType}}</label>
        </div>

    </div>
    <div class="col-md-6">
        <div v-if="showcustomApplyLink" class="form-group ">
            <label>{{applyLinkLabel}}</label>
            <input type="text" class="form-control">
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-6">
        <div class="form-group ">
            <label for="jobTitle">How did you hear about <?= GeneralService::APP_NAME ?> </label>
            <select style="width: 100%;" @change="onChangeMarketing" class="form-control" v-model="selectedMarketing" data-placeholder="Select a Work place type" data-allow-clear="true">

                <option v-for="market in marketing" :value="market.id">{{market.market}}</option>


            </select>

        </div>
    </div>
    <div v-if="isMarketingOthers" class="col-md-6">
        <div class="form-group ">
            <label>Others (Provide info) </label>
            <input type="text" class="form-control" id="jobTitle" ref="vOtherMarketing" placeholder="Job Title e.g Web Developer">
        </div>
    </div>
</div>

<hr>