<div class="row">
    <div class="col-md-12">


        <div class="form-group">
            <label>Tell us about the Role</label>
            <quill-editor ref="vjDesc" rows="5" contentType="html" theme="snow"></quill-editor>
        </div>
    </div>

</div>


<hr>
<div class="row">
    <div class="col-md-6">
        <div class="form-group static required">
            <label for="exampleInputEmail1">Add Skills</label>
            <div class="row">
                <div class="col-md-9 col-xs-9">
                    <input @input="searchskills()" v-model="skillSearchParameter" type="" class="form-control" id="" placeholder="Search For skills">
                </div>
                <div class="col-md-3 col-xs-3"><button><i class="fa fa-plus"></i></button></div>
            </div>
            <div class="row">

                <ul style="border: 0.5px solid grey" v-if="skillsearchResult.length" class="select2-results" role="listbox" id="select2-results-2">



                    <li v-for="result in skillsearchResult" class="select2-results-dept-1 select2-result select2-result-selectable" role="presentation">
                        <div class="select2-result-label" id="select2-result-label-15" role="option"><button @click="onSelectSkill({id: result.id, name: result.skill})" class="btn btn-white btn-block"><span class="select2-match"></span>{{result.skill}}</button></div>
                    </li>



                </ul>
            </div>
        </div>
    </div>
    <div class="col-md-6">
        <div class="item">
            <div v-show="selectedSkills.length" class="panel panel-default paper-shadow" data-z="0.5">
                <div class="panel-heading">
                    <div class="media v-middle">
                        <div class="media-body">

                            <p class="text-subhead text-light">Selected Skills</p>
                        </div>

                    </div>
                </div>
                <div class="table-responsive">
                    <table class="table text-subhead v-middle">
                        <thead>
                            <th class="text-subhead  text-center" style="font-size: 10px;">Skill</th>
                            <th class="text-subhead  text-center" style="font-size: 10px;">Skill Required</th>
                            <th class="text-subhead  text-center" style="font-size: 10px;">Years of experience(min)</th>
                        </thead>
                        <tbody>
                            <tr v-for="(skill, index) in selectedSkills">
                                <td class="width-100 text-caption">
                                    <div class="label label-grey-200 label-xs">{{skill.name}}</div>
                                </td>

                                <td class="width-100 text-center"><a href="#"><input type="checkbox"></a></td>
                                <td class="width-100 text-center"><input ref="skillMinYears" type="text" class="form-control"></td>
                                <td><button @click="onRemoveFromSelectedSkill(index)" class="btn btn-danger"><i class="fa fa-close"></i></button></td>
                            </tr>

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<hr>

<div class="row">

    <h3>Add screening questions</h3>
    <div class="panel panel-default">
        <div class="panel-body buttons-spacing-vertical">
            <p>
                <button class="btn btn-success" v-for="(question, index) in jobScreeningQuestions" @click="onSelectJobScreeningQuestions(index, question)"><i class="fa fa-plus"></i> {{question.screenQuestions}}</button>
            </p>

        </div>
    </div>
    <div v-if="selectedJobScreeningQuestions.length" class="panel panel-default">
        <div class="panel panel-default">
            <div class="media v-middle">
                <div class="media-left">
                    <div class="bg-green-400 text-white">
                        <div class="panel-body">
                            <i class="fa fa-gear fa-fw "></i>
                        </div>
                    </div>
                </div>
                <div class="media-body">
                    <span class="text-body-2"><em>Qualification Settings: </span> Filter out and send rejections to applicants who dont meet any must-have qualifications</em>
                </div>
                <div class="media-right media-padding">
                    <input type="checkbox" ref="isFilterQualificationSetting">
                </div>
            </div>
        </div>
        <div class="panel-body buttons-spacing-vertical">
            <div v-for="(select, index) in selectedJobScreeningQuestions">
                <button class="btn btn-primary" @click="onRemoveJobScreenQuestions(index, select)"><i class="fa fa-trash"></i> {{select.screenQuestions}} </button><br>
                <p>{{select.associatedQuestion}}</p>
            </div>
        </div>
    </div>
</div>

<br>