<?php

use Application\Service\ApplicationService;

?>
<?= $this->doctype() ?>
<html lang="en">

<head>
    <meta charset="utf-8">
    <?= $this->headTitle(ApplicationService::APP_NAME)->setSeparator(' - ')->setAutoEscape(false) ?>

    <!-- Font Awesome Icons -->
    <script src="https://kit.fontawesome.com/42d5adcbca.js" crossorigin="anonymous"></script>
    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?= $this->headLink([
        'rel' => 'shortcut icon',
        'type' => 'image/vnd.microsoft.icon',
        'href' => $this->basePath() . '/img/favicon.ico'
    ])
        ->prependStylesheet("https://cdn.jsdelivr.net/npm/sweetalert2@11/dist/sweetalert2.min.css")
        ->prependStylesheet($this->basePath("soft/assets/css/soft-ui-dashboard.css?v=1.0.6"))
        ->prependStylesheet($this->basePath("soft/assets/css/nucleo-svg.css"))
        ->prependStylesheet($this->basePath("soft/assets/css/nucleo-svg.css"))
        ->prependStylesheet($this->basePath("soft/assets/css/nucleo-icons.css"))
        ->prependStylesheet("https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700")

    ?>

    <script src="https://unpkg.com/vue@3/dist/vue.global.js"></script>
    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>

    <script src="https://cdn.jsdelivr.net/npm/vue-toast-notification@3"></script>
    <link href="https://cdn.jsdelivr.net/npm/vue-toast-notification@3/dist/theme-sugar.css" rel="stylesheet">

    <!-- Scripts -->
    <?= $this->headScript() ?>
</head>

<body class="error-page">
    <!-- Navbar -->

    <!-- End Navbar -->
    <main class="main-content  mt-0">
        <section class="my-10">
            <div class="container">
                <div class="row">
                    <div class="col-lg-6 my-auto">
                        <h1 class="display-1 text-bolder text-gradient text-danger">Ooops... Error </h1>
                        <h2>Erm. You dont have access</h2>
                        <p class="lead">We suggest you to go to the homepage while we solve this issue.</p>
                        <a href="<?= $this->url("actor") ?>" type="button" class="btn bg-gradient-dark mt-4">Go
                            to
                            Homepage</a>
                    </div>
                    <div class="col-lg-6 my-auto position-relative">
                        <img class="w-100 position-relative" src="/soft/assets/img/illustrations/error-404.png"
                            alt="404-error">
                    </div>
                </div>
            </div>
        </section>
    </main>
    <!-- -------- START FOOTER 3 w/ COMPANY DESCRIPTION WITH LINKS & SOCIAL ICONS & COPYRIGHT ------- -->

    <!-- -------- END FOOTER 3 w/ COMPANY DESCRIPTION WITH LINKS & SOCIAL ICONS & COPYRIGHT ------- -->
    <!--   Core JS Files   -->

</body>



</html>