<?php echo $this->headtitle("Create Newsletter") ?>
<div id="anews" class="row">
    <div class="col-lg-9 col-12 mx-auto">
        <div class="card card-body mt-4">
            <h6 class="mb-0">NewsLetter </h6>
            <p class="text-sm mb-0">Create NewsLetter</p>
            <hr class="horizontal dark my-3">
            <label for="projectName" class="form-label">Topic</label>
            <input type="text" v-model="topic" class="form-control" id="projectName">
            <div class="row mt-4">
                <div class="col-12 col-md-6">
                    <div class="form-group">
                        <label>
                            Private Project
                        </label>
                        <p class="form-text text-muted text-xs ms-1">
                            If you are available for hire outside of the current situation, you can encourage others to hire you.
                        </p>
                        <div class="form-check form-switch ms-1">
                            <input class="form-check-input" type="checkbox" id="flexSwitchCheckDefault" onclick="notify(this)" data-type="warning" data-content="Once a project is made private, you cannot revert it to a public project." data-title="Warning" data-icon="ni ni-bell-55">
                            <label class="form-check-label" for="flexSwitchCheckDefault"></label>
                        </div>
                    </div>
                </div>
            </div>
            <label class="mt-4">Project Description</label>
            <p class="form-text text-muted text-xs ms-1">
                This is how others will learn about the project, so make it good!
            </p>
            <quill-editor ref="myee" v-model:content="contentss" contentType="html" theme="snow"></quill-editor>
            <label class="mt-4 form-label">Newsletter Category</label>
            <select class="form-control" name="choices-multiple-remove-button" id="choices-multiple-remove-button" multiple>
                <option value="Choice 1" selected>Choice 1</option>
                <option value="Choice 2">Choice 2</option>
                <option value="Choice 3">Choice 3</option>
                <option value="Choice 4">Choice 4</option>
            </select>
            <div class="row">
                <div class="col-6">
                    <label class="form-label">Start Date</label>
                    <input class="form-control datetimepicker" type="text" placeholder="Please select start date" data-input>
                </div>
                <div class="col-6">
                    <label class="form-label">End Date</label>
                    <input class="form-control datetimepicker" type="text" placeholder="Please select end date" data-input>
                </div>
            </div>
            <label class="mt-4 form-label">Starting Files</label>
            <form action="/file-upload" class="form-control dropzone" id="dropzone">
                <div class="fallback">
                    <input name="file" type="file" multiple />
                </div>
            </form>
            <div class="d-flex justify-content-end mt-4">
                <button type="button" name="button" class="btn btn-light m-0">Cancel</button>
                <button type="button" name="button" class="btn bg-gradient-primary m-0 ms-2">Create Project</button>
            </div>
        </div>
    </div>
</div>
<script>
    const aNewsApp = Vue.createApp({
        data() {
            return {
                key: 'value',
                topic: "",
            }
        },
        methods: {
            getNewletterCategory() {
                axios.get("/apps/news/web/get-newsletter-category").then((result) => {
                    if (result.status == 200) {
                        console.log(result.data.data);
                    }
                }).catch((err) => {

                });
            }
        },
    });
    aNewsApp.component('QuillEditor', VueQuill.QuillEditor);
    aNewsApp.mount("#anews")
</script>



<?php $this->inlineScript()->appendFile($this->basePath('soft/js/core/popper.min.js'))
    ->appendFile($this->basePath('soft/js/core/bootstrap.min.js'))
    ->appendFile($this->basePath('soft/js/plugins/perfect-scrollbar.min.js'))
    ->appendFile($this->basePath('soft/js/plugins/smooth-scrollbar.min.js'))
    ->appendFile($this->basePath('soft/js/plugins/choices.min.js'))
    ->appendFile($this->basePath('soft/js/plugins/quill.min.js'))
    ->appendFile($this->basePath('soft/js/plugins/flatpickr.min.js'))
    ->appendFile($this->basePath('soft/js/plugins/dropzone.min.js'))
    ->appendFile($this->basePath('soft/js/plugins/dragula/dragula.min.js'))
    ->appendFile($this->basePath('soft/js/plugins/jkanban/jkanban.js')); ?>

<script async defer src="https://buttons.github.io/buttons.js"></script>