<?php echo $this->headtitle("Recruiter Post job"); ?>

<link rel="stylesheet" href="https://unpkg.com/vue3-form-wizard/dist/style.css">
<link rel="stylesheet" href="https://unpkg.com/@vueup/vue-quill@1.2.0/dist/vue-quill.snow.prod.css">
<div id="postjob">
    <div class="parallax overflow-hidden bg-blue-400 page-section third">
        <div class="container parallax-layer" data-opacity="true">
            <div class="media v-middle">
                <div class="media-left text-center">

                </div>
                <div class="media-body">
                    <h1 class="text-white text-display-1 margin-v-0">John Doe</h1>

                </div>

            </div>
        </div>
    </div>


    <div class="parallax bg-white page-section third">
        <div class="container parallax-layer" data-opacity="true">
            <div class="media v-middle media-overflow-visible">
                <div class="media-left">
                    <span class="icon-block s30 bg-lightred"><i class="fa fa-github"></i></span>
                </div>
                <div class="media-body">
                    <div class="text-headline">Github Webhooks for Beginners</div>
                </div>
                <div class="media-right">
                    <div class="dropdown">
                        <a class="btn btn-white dropdown-toggle" data-toggle="dropdown" href="#">Course <span class="caret"></span></a>
                        <ul class="dropdown-menu pull-right">
                            <li><a href="">Something</a></li>
                            <li><a href="">Something else</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="container">

        <div class="page-section">
            <div class="row">



                <div class="col-md-9">

                    <h2 class="page-section-heading">Post a Job</h2>
                    <div class="panel panel-default">
                        <div class="panel-body">

                            <form-wizard @on-complete="onComplete" @on-validate="handleValidation" @on-loading="setLoading" color="#064E3B">
                                <tab-content :before-change="validateAsync" title="Basic Job info">

                                    <?= $this->partial("recruiterPartial-basic-form-job-info") ?>

                                </tab-content>
                                <tab-content :before-change="validateAsync" title="Job Description">
                                    <?= $this->partial("recruiterPartial-job-description-form"); ?>
                                </tab-content>
                                <tab-content title="Overview">
                                    Overview
                                </tab-content>
                                <div class="loader" v-if="loadingWizard"></div>
                            </form-wizard>

                        </div>
                    </div>




                    <br />
                    <br />

                </div>
                <div class="col-md-3">

                    <div class="panel panel-default" data-toggle="panel-collapse" data-open="true">
                        <div class="panel-heading panel-collapse-trigger">
                            <h4 class="panel-title">Resources</h4>
                        </div>
                        <div class="panel-body list-group">
                            <ul class="list-group list-group-menu">
                                <li class="list-group-item active"><a class="link-text-color" href="website-take-course.html">Curriculum</a></li>
                                <li class="list-group-item"><a class="link-text-color" href="website-course-forums.html">Course Forums</a></li>
                                <li class="list-group-item"><a class="link-text-color" href="website-take-quiz.html">Take Quiz</a></li>
                                <li class="list-group-item"><a class="link-text-color" href="website-quiz-results.html">Quiz Results</a></li>
                            </ul>
                        </div>
                    </div>

                    <div class="panel panel-default" data-toggle="panel-collapse" data-open="true">
                        <div class="panel-heading panel-collapse-trigger">
                            <h4 class="panel-title">Instructor</h4>
                        </div>
                        <div class="panel-body">
                            <div class="media v-middle">
                                <div class="media-left">
                                    <img src="images/people/110/guy-6.jpg" alt="About Adrian" width="60" class="img-circle" />
                                </div>
                                <div class="media-body">
                                    <h4 class="text-title margin-none"><a href="#">Adrian Demian</a></h4>
                                    <span class="caption text-light">Biography</span>
                                </div>
                            </div>
                            <br />
                            <div class="expandable expandable-indicator-white expandable-trigger">
                                <div class="expandable-content">
                                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. A accusamus aut consectetur consequatur cum cupiditate debitis doloribus, error ex explicabo harum illum minima mollitia nisi nostrum officiis omnis optio qui quisquam saepe sit
                                        sunt totam vel velit voluptatibus? Adipisci ducimus expedita id nostrum quas quia!</p>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>

            </div>
        </div>

    </div>
</div>
<script src="https://unpkg.com/vue3-form-wizard"></script>
<script src="https://unpkg.com/@vueup/vue-quill@1.2.0"></script>
<style>
    .loader,
    .loader:after {
        border-radius: 50%;
        width: 10em;
        height: 10em;
    }

    .loader {
        margin: 60px auto;
        font-size: 10px;
        position: relative;
        text-indent: -9999em;
        border-top: 1.1em solid rgba(255, 255, 255, 0.2);
        border-right: 1.1em solid rgba(255, 255, 255, 0.2);
        border-bottom: 1.1em solid rgba(255, 255, 255, 0.2);
        border-left: 1.1em solid #064E3B;
        -webkit-transform: translateZ(0);
        -ms-transform: translateZ(0);
        transform: translateZ(0);
        -webkit-animation: load8 1.1s infinite linear;
        animation: load8 1.1s infinite linear;
    }

    @-webkit-keyframes load8 {
        0% {
            -webkit-transform: rotate(0deg);
            transform: rotate(0deg);
        }

        100% {
            -webkit-transform: rotate(360deg);
            transform: rotate(360deg);
        }
    }

    @keyframes load8 {
        0% {
            -webkit-transform: rotate(0deg);
            transform: rotate(0deg);
        }

        100% {
            -webkit-transform: rotate(360deg);
            transform: rotate(360deg);
        }
    }
</style>
<script>
    const postJobApp = Vue.createApp({
        data() {
            return {
                postjobs: [],
                jobTitle: "",
                jobDescrpption: "",
                jobType: "",
                jobWorkplaceType: "",
                jobLocation: "",
                skills: [],
                qualifications: [],
                isValid: false,
                activeTab: 0,
                loadingWizard: false
            }
        },

        mounted() {
            this.getWorkType();
        },

        methods: {
            setLoading: function(value) {
                this.loadingWizard = value
            },

            validateJobTitle() {

            },

            getWorkType() {

            },

            validateBasic() {

            },

            changeMade(prevIndex, nextIndex) {
                console.log('Previous: ' + prevIndex + ' Next: ' + nextIndex)

            },

            handleValidation(isValid, tabIndex) {
                console.log('Tab: ' + tabIndex + ' valid: ' + isValid)
                this.activeTab = tabIndex;
            },

            validateAsync() {
                return new Promise((resolve, reject) => {
                    setTimeout(() => {

                        // if (this.previousTab < this.nextTab) {
                        if (this.activeTab == 0) {
                            if (this.jobTitle == "") {
                                this.$toast.open({
                                    message: "Title is required",
                                    type: "error",
                                    position: "top-left",
                                    duration: 20000,
                                    dismissible: true
                                });
                                resolve(false);
                            }
                        } else if (this.activeTab == 1) {

                        }

                        // }


                    }, 1000)
                })
                // this.$emit('on-complete');
                // return true;
            },

            validateBasicForm() {

            },

            validateForm(isValid, tabIndex) {
                console.log('Tab: ' + tabIndex + ' valid: ' + isValid)
            },



            // When all validation is true
            onComplete() {
                alert("come home");
            }
        },
    });

    postJobApp.component("FormWizard", Vue3FormWizard.FormWizard)
    postJobApp.component("TabContent", Vue3FormWizard.TabContent)
    postJobApp.use(VueToast.ToastPlugin);
    postJobApp.component('QuillEditor', VueQuill.QuillEditor);
    postJobApp.use(Vue3FormWizard)
    postJobApp.mount("#postjob")
</script>