<?php

use General\Service\GeneralService;

?>
<?= $this->doctype() ?>
<html lang="en" class="light scroll-smooth" dir="ltr">

<head>
    <meta charset="utf-8">
    <?= $this->headTitle(GeneralService::APP_NAME)->setSeparator(' - ')->setAutoEscape(false) ?>

    <!-- Font Awesome Icons -->
    <script src="https://kit.fontawesome.com/42d5adcbca.js" crossorigin="anonymous"></script>
    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?= $this->headLink([
        'rel' => 'shortcut icon',
        'type' => 'image/vnd.microsoft.icon',
        'href' => $this->basePath() . '/img/favicon.ico'
    ])


        ->prependStylesheet($this->basePath("assets/css/tailwind.css"))
        ->prependStylesheet($this->basePath("assets/libs/tiny-slider/tiny-slider.css"))
        ->prependStylesheet($this->basePath("assets/libs/@mdi/font/css/materialdesignicons.min.css"))
        ->prependStylesheet($this->basePath("assets/libs/@iconscout/unicons/css/line.css"))
        ->prependStylesheet($this->basePath("assets/libs/choices.js/public/assets/styles/choices.min.css"))
        ->prependStylesheet($this->basePath("assets/libs/tobii/css/tobii.min.css"))

    ?>

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" />

    <!-- Font Awesome Link -->

    <!-- script -->

    <script src="https://unpkg.com/@material-tailwind/html@latest/scripts/ripple.js"></script>

    <script src="https://unpkg.com/vue@3/dist/vue.global.js"></script>
    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

    <script src="https://cdn.jsdelivr.net/npm/vue-toast-notification@3"></script>


    <!-- Scripts -->

</head>

<body class="dark:bg-slate-900">

    <nav id="topnav" class="defaultscroll is-sticky">
        <div class="container">
            <!-- Logo container-->
            <a class="logo" href="index.html">
                <div class="block sm:hidden">
                    <img src="assets/images/logo-icon-40.png" class="h-10 inline-block dark:hidden" alt="">
                    <img src="assets/images/logo-icon-40-white.png" class="h-10 hidden dark:inline-block" alt="">
                </div>
                <div class="sm:block hidden">
                    <img src="assets/images/logo-dark.png" class="h-[24px] inline-block dark:hidden" alt="">
                    <img src="assets/images/logo-white.png" class="h-[24px] hidden dark:inline-block" alt="">
                </div>
            </a>
            <!-- End Logo container-->

            <!-- Start Mobile Toggle -->
            <div class="menu-extras">
                <div class="menu-item">
                    <a class="navbar-toggle" id="isToggle" onclick="toggleMenu()">
                        <div class="lines">
                            <span></span>
                            <span></span>
                            <span></span>
                        </div>
                    </a>
                </div>
            </div>
            <!-- End Mobile Toggle -->

            <!--Login button Start-->
            <ul class="buy-button list-none mb-0">
                <li class="inline-block mb-0">
                    <div class="relative top-[3px]">
                        <i class="uil uil-search text-lg absolute top-[3px] end-3"></i>
                        <input type="text" class="form-input h-9 pe-10 rounded-3xl sm:w-44 w-36 border-gray-100 dark:border-slate-800 bg-white dark:bg-slate-900" name="s" id="searchItem" placeholder="Search...">
                    </div>
                </li>

                <li class="dropdown inline-block relative ps-1">
                    <?php if ($this->identity()) : ?>
                        <button data-dropdown-toggle="dropdown" class="dropdown-toggle items-center" type="button">
                            <span class="btn btn-icon rounded-full bg-emerald-600 hover:bg-emerald-700 border-emerald-600 hover:border-emerald-700 text-white"><img src="assets/images/team/01.jpg" class="rounded-full" alt=""></span>
                        </button>
                        <!-- Dropdown menu -->
                        <div class="dropdown-menu absolute end-0 m-0 mt-4 z-10 w-44 rounded-md overflow-hidden bg-white dark:bg-slate-900 shadow dark:shadow-gray-700 hidden" onclick="event.stopPropagation();">
                            <ul class="py-2 text-start">
                                <li>
                                    <a href="candidate-profile.html" class="flex items-center font-medium py-2 px-4 dark:text-white/70 hover:text-emerald-600 dark:hover:text-white"><i data-feather="user" class="h-4 w-4 me-2"></i>Profile</a>
                                </li>
                                <li>
                                    <a href="candidate-profile-setting.html" class="flex items-center font-medium py-2 px-4 dark:text-white/70 hover:text-emerald-600 dark:hover:text-white"><i data-feather="settings" class="h-4 w-4 me-2"></i>Settings</a>
                                </li>
                                <li class="border-t border-gray-100 dark:border-gray-800 my-2"></li>
                                <li>
                                    <a href="lock-screen.html" class="flex items-center font-medium py-2 px-4 dark:text-white/70 hover:text-emerald-600 dark:hover:text-white"><i data-feather="lock" class="h-4 w-4 me-2"></i>Lockscreen</a>
                                </li>
                                <li>
                                    <a href="login.html" class="flex items-center font-medium py-2 px-4 dark:text-white/70 hover:text-emerald-600 dark:hover:text-white"><i data-feather="log-out" class="h-4 w-4 me-2"></i>Logout</a>
                                </li>
                            </ul>
                        </div>
                    <?php else : ?>
                        <button data-dropdown-toggle="dropdown" class="dropdown-toggle items-center" type="button">
                            <span class="btn btn-icon rounded-full bg-emerald-600 hover:bg-emerald-700 border-emerald-600 hover:border-emerald-700 text-white"><img src="/img/no.png" class="rounded-full" alt=""></span>
                        </button>
                        <!-- Dropdown menu -->
                        <div class="dropdown-menu absolute end-0 m-0 mt-4 z-10 w-44 rounded-md overflow-hidden bg-white dark:bg-slate-900 shadow dark:shadow-gray-700 hidden" onclick="event.stopPropagation();">
                            <ul class="py-2 text-start">
                                <li>
                                    <a href="<?= $this->url("login") ?>" class="flex items-center font-medium py-2 px-4 dark:text-white/70 hover:text-emerald-600 dark:hover:text-white"><i data-feather="user" class="h-4 w-4 me-2"></i>Login</a>
                                </li>
                                <li class="border-t border-gray-100 dark:border-gray-800 my-2"></li>
                                <li>
                                    <a href="<?= $this->url("register") ?>" class="flex items-center font-medium py-2 px-4 dark:text-white/70 hover:text-emerald-600 dark:hover:text-white"><i data-feather="settings" class="h-4 w-4 me-2"></i>Job Seeker</a>
                                </li>

                                <li>
                                    <a href="<?= $this->url("authentication", ["controller" => "recruiter", "action" => "register"]) ?>" class="flex items-center font-medium py-2 px-4 dark:text-white/70 hover:text-emerald-600 dark:hover:text-white"><i data-feather="settings" class="h-4 w-4 me-2"></i>Recruiter</a>
                                </li>
                            </ul>
                        </div>

                    <?php endif; ?>
                </li><!--end dropdown-->
            </ul>
            <!--Login button End-->

            <div id="navigation">
                <!-- Navigation Menu-->
                <ul class="navigation-menu justify-end">
                    <li class="has-submenu parent-menu-item">
                        <a href="javascript:void(0)">Home</a><span class="menu-arrow"></span>
                        <ul class="submenu">
                            <li><a href="index.html" class="sub-menu-item">Hero One</a></li>
                            <li><a href="index-two.html" class="sub-menu-item">Hero Two</a></li>
                            <li><a href="index-three.html" class="sub-menu-item">Hero Three</a></li>
                            <li><a href="index-four.html" class="sub-menu-item">Hero Four</a></li>
                            <li><a href="index-five.html" class="sub-menu-item">Hero Five</a></li>
                            <li><a href="index-six.html" class="sub-menu-item">Hero Six </a></li>
                            <li><a href="index-seven.html" class="sub-menu-item">Hero Seven </a></li>
                            <li><a href="index-eight.html" class="sub-menu-item">Hero Eight <span class="bg-yellow-500 inline-block text-white text-[10px] font-bold px-2.5 py-0.5 rounded h-5 ms-1">New</span></a></li>
                        </ul>
                    </li>

                    <li class="has-submenu parent-parent-menu-item"><a href="javascript:void(0)"> Services </a><span class="menu-arrow"></span>
                        <ul class="submenu">
                            <li><a href="<?= $this->url("app", ["controller" => "application", "action" => "lazy-applicant"]) ?>" class="sub-menu-item">Lazy Applicant</a></li>
                            <li><a href="<?= $this->url("app", ["controller" => "application", "action" => "career-service"]) ?>" class="sub-menu-item">Lazy Applicant</a></li>

                            <li class="has-submenu parent-menu-item">
                                <a href="javascript:void(0)"> Job Grids </a><span class="submenu-arrow"></span>
                                <ul class="submenu">
                                    <li><a href="job-grid-one.html" class="sub-menu-item">Job Grid One</a></li>
                                    <li><a href="job-grid-two.html" class="sub-menu-item">Job Grid Two</a></li>
                                    <li><a href="job-grid-three.html" class="sub-menu-item">Job Grid Three</a></li>
                                    <li><a href="job-grid-four.html" class="sub-menu-item">Job Grid Four </a></li>
                                </ul>
                            </li>

                            <li class="has-submenu parent-menu-item">
                                <a href="javascript:void(0)"> Job Lists </a><span class="submenu-arrow"></span>
                                <ul class="submenu">
                                    <li><a href="job-list-one.html" class="sub-menu-item">Job List One</a></li>
                                    <li><a href="job-list-two.html" class="sub-menu-item">Job List Two</a></li>
                                    <li><a href="job-list-three.html" class="sub-menu-item">Job List Three</a></li>
                                    <li><a href="job-list-four.html" class="sub-menu-item">Job List Four</a></li>
                                    <li><a href="job-list-five.html" class="sub-menu-item">Job List Five </a></li>
                                    <li><a href="job-list-six.html" class="sub-menu-item">Job List Six </a></li>
                                </ul>
                            </li>

                            <li class="has-submenu parent-menu-item">
                                <a href="javascript:void(0)"> Job Detail </a><span class="submenu-arrow"></span>
                                <ul class="submenu">
                                    <li><a href="job-detail-one.html" class="sub-menu-item">Job Detail One</a></li>
                                    <li><a href="job-detail-two.html" class="sub-menu-item">Job Detail Two</a></li>
                                    <li><a href="job-detail-three.html" class="sub-menu-item">Job Detail Three</a></li>
                                </ul>
                            </li>

                            <li><a href="job-apply.html" class="sub-menu-item">Job Apply</a></li>

                            <li><a href="job-post.html" class="sub-menu-item">Job Post </a></li>

                            <li><a href="career.html" class="sub-menu-item">Career </a></li>
                        </ul>
                    </li>

                    <li class="has-submenu parent-parent-menu-item"><a href="javascript:void(0)"> Jobs </a><span class="menu-arrow"></span>
                        <ul class="submenu">
                            <li><a href="job-categories.html" class="sub-menu-item">Job Categories</a></li>

                            <li class="has-submenu parent-menu-item">
                                <a href="javascript:void(0)"> Job Grids </a><span class="submenu-arrow"></span>
                                <ul class="submenu">
                                    <li><a href="job-grid-one.html" class="sub-menu-item">Job Grid One</a></li>
                                    <li><a href="job-grid-two.html" class="sub-menu-item">Job Grid Two</a></li>
                                    <li><a href="job-grid-three.html" class="sub-menu-item">Job Grid Three</a></li>
                                    <li><a href="job-grid-four.html" class="sub-menu-item">Job Grid Four </a></li>
                                </ul>
                            </li>

                            <li class="has-submenu parent-menu-item">
                                <a href="javascript:void(0)"> Job Lists </a><span class="submenu-arrow"></span>
                                <ul class="submenu">
                                    <li><a href="job-list-one.html" class="sub-menu-item">Job List One</a></li>
                                    <li><a href="job-list-two.html" class="sub-menu-item">Job List Two</a></li>
                                    <li><a href="job-list-three.html" class="sub-menu-item">Job List Three</a></li>
                                    <li><a href="job-list-four.html" class="sub-menu-item">Job List Four</a></li>
                                    <li><a href="job-list-five.html" class="sub-menu-item">Job List Five </a></li>
                                    <li><a href="job-list-six.html" class="sub-menu-item">Job List Six </a></li>
                                </ul>
                            </li>

                            <li class="has-submenu parent-menu-item">
                                <a href="javascript:void(0)"> Job Detail </a><span class="submenu-arrow"></span>
                                <ul class="submenu">
                                    <li><a href="job-detail-one.html" class="sub-menu-item">Job Detail One</a></li>
                                    <li><a href="job-detail-two.html" class="sub-menu-item">Job Detail Two</a></li>
                                    <li><a href="job-detail-three.html" class="sub-menu-item">Job Detail Three</a></li>
                                </ul>
                            </li>

                            <li><a href="job-apply.html" class="sub-menu-item">Job Apply</a></li>

                            <li><a href="job-post.html" class="sub-menu-item">Job Post </a></li>

                            <li><a href="career.html" class="sub-menu-item">Career </a></li>
                        </ul>
                    </li>

                    <li class="has-submenu parent-parent-menu-item">
                        <a href="javascript:void(0)">Pages</a><span class="menu-arrow"></span>
                        <ul class="submenu">
                            <li><a href="aboutus.html" class="sub-menu-item">About Us</a></li>
                            <li><a href="services.html" class="sub-menu-item">Services</a></li>
                            <li><a href="pricing.html" class="sub-menu-item">Pricing </a></li>

                            <li class="has-submenu parent-menu-item">
                                <a href="javascript:void(0)">Employers</a><span class="submenu-arrow"></span>
                                <ul class="submenu">
                                    <li><a href="employer-list.html" class="sub-menu-item">Employers</a></li>
                                    <li><a href="employer-profile.html" class="sub-menu-item">Employer Profile</a></li>
                                </ul>
                            </li>

                            <li class="has-submenu parent-menu-item">
                                <a href="javascript:void(0)">Candidates <span class="bg-yellow-500 inline-block text-white text-[10px] font-bold px-2.5 py-0.5 rounded h-5 ms-1">New</span></a><span class="submenu-arrow"></span>
                                <ul class="submenu">
                                    <li><a href="candidate-list.html" class="sub-menu-item">Candidates</a></li>
                                    <li><a href="candidate-profile.html" class="sub-menu-item">Candidate Profile</a></li>
                                    <li><a href="candidate-profile-setting.html" class="sub-menu-item">Profile Settings <span class="bg-yellow-500 inline-block text-white text-[10px] font-bold px-2.5 py-0.5 rounded h-5 ms-1">New</span></a></li>
                                </ul>
                            </li>

                            <li class="has-submenu parent-menu-item">
                                <a href="javascript:void(0)"> Helpcenter </a><span class="submenu-arrow"></span>
                                <ul class="submenu">
                                    <li><a href="helpcenter-overview.html" class="sub-menu-item">Overview</a></li>
                                    <li><a href="helpcenter-faqs.html" class="sub-menu-item">FAQs</a></li>
                                    <li><a href="helpcenter-guides.html" class="sub-menu-item">Guides</a></li>
                                    <li><a href="helpcenter-support.html" class="sub-menu-item">Support</a></li>
                                </ul>
                            </li>

                            <li class="has-submenu parent-menu-item"><a href="javascript:void(0)"> Blog </a><span class="submenu-arrow"></span>
                                <ul class="submenu">
                                    <li><a href="blogs.html" class="sub-menu-item"> Blogs</a></li>
                                    <li><a href="blog-detail.html" class="sub-menu-item"> Blog Detail</a></li>
                                </ul>
                            </li>

                            <li class="has-submenu parent-menu-item"><a href="javascript:void(0)"> Auth Pages </a><span class="submenu-arrow"></span>
                                <ul class="submenu">
                                    <li><a href="login.html" class="sub-menu-item"> Login</a></li>
                                    <li><a href="signup.html" class="sub-menu-item"> Signup</a></li>
                                    <li><a href="reset-password.html" class="sub-menu-item"> Forgot Password</a></li>
                                    <li><a href="lock-screen.html" class="sub-menu-item"> Lock Screen</a></li>
                                </ul>
                            </li>

                            <li class="has-submenu parent-menu-item"><a href="javascript:void(0)"> Utility </a><span class="submenu-arrow"></span>
                                <ul class="submenu">
                                    <li><a href="terms.html" class="sub-menu-item">Terms of Services</a></li>
                                    <li><a href="privacy.html" class="sub-menu-item">Privacy Policy</a></li>
                                </ul>
                            </li>

                            <li class="has-submenu parent-menu-item"><a href="javascript:void(0)"> Special </a><span class="submenu-arrow"></span>
                                <ul class="submenu">
                                    <li><a href="comingsoon.html" class="sub-menu-item"> Coming Soon</a></li>
                                    <li><a href="maintenance.html" class="sub-menu-item"> Maintenance</a></li>
                                    <li><a href="error.html" class="sub-menu-item"> 404!</a></li>
                                    <li><a href="thankyou.html" class="sub-menu-item"> Thank you</a></li>
                                </ul>
                            </li>
                        </ul>
                    </li>

                    <li><a href="contact.html" class="sub-menu-item">Contact</a></li>
                </ul><!--end navigation menu-->
            </div><!--end navigation-->
        </div><!--end container-->
    </nav><!--end header-->
    <!-- Loader Start -->
    <!-- <div id="preloader">
            <div id="status">
                <div class="spinner">
                    <div class="double-bounce1"></div>
                    <div class="double-bounce2"></div>
                </div>
            </div>
        </div> -->
    <!-- Loader End -->

    <?php
    $flashMessenger = $this->flashMessenger()
        ->setMessageOpenFormat('<div%s  role="alert">
               
             
     <ul><li>')

        ->setMessageCloseString('</div>');
    ?>
    <?php echo $flashMessenger->render('error', ['p-4 mb-4', 'text-sm text-red-800', 'rounded-lg', 'bg-red-50', 'dark:bg-gray-800', 'dark:text-red-400']); ?>
    <?php echo $flashMessenger->render('info', ['alert', 'p-4 mb-4', 'text-sm text-blue-800', 'rounded-lg', 'bg-blue-50', 'dark:bg-gray-800', 'dark:text-blue-400']); ?>
    <?php echo $flashMessenger->render('default', ['alert', 'p-4 mb-4', 'text-sm text-yellow-800', 'rounded-lg', 'bg-yellow-50', 'dark:bg-gray-800', 'dark:text-yellow-400']); ?>
    <?php echo $flashMessenger->render('success', ['alert', 'p-4 mb-4', 'text-sm text-green-800', 'rounded-lg', 'bg-green-50', 'dark:bg-gray-800', 'dark:text-green-400']); ?>


    <?= $this->content ?>
    <section class="relative md:py-24 py-16">
        <div class="container">
            <div class="grid md:grid-cols-12 grid-cols-1 pb-8 items-end">
                <div class="lg:col-span-8 md:col-span-6">
                    <h3 class="mb-4 md:text-[26px] md:leading-normal text-2xl leading-normal font-semibold">Terces Academy</h3>
                </div>
            </div><!--end grid-->

            <div class="grid grid-cols-1 mt-7 relative">
                <div class="tiny-five-item">
                    <div class="tiny-slide">
                        <div class="group relative overflow-hidden rounded-md shadow dark:shadow-gray-700 transition duration-500 m-1">
                            <img src="/assets/images/work/01.jpg" alt="">
                            <div class="absolute inset-0 bg-slate-900/50"></div>

                            <div class="absolute bottom-0 p-4">
                                <a href="" class="text-lg font-semibold text-white hover:text-emerald-600 transition-all duration-500">Product & Branding Design</a>
                            </div>
                        </div>
                    </div>



                    <div class="tiny-slide">
                        <div class="group relative overflow-hidden rounded-md shadow dark:shadow-gray-700 transition duration-500 m-1">
                            <img src="/assets/images/work/06.jpg" alt="">
                            <div class="absolute inset-0 bg-slate-900/50"></div>

                            <div class="absolute bottom-0 p-4">
                                <a href="" class="text-lg font-semibold text-white hover:text-emerald-600 transition-all duration-500">Digital Marketing</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div><!--grid-->
        </div><!--end container-->
        <div class="container-fluid md:mt-24 mt-16">
            <div class="container">
                <div class="grid grid-cols-1">
                    <div class="relative overflow-hidden lg:px-8 px-6 py-10 rounded-xl shadow-lg dark:shadow-gray-700">
                        <div class="grid md:grid-cols-12 grid-cols-1 items-center gap-[30px]">
                            <div class="lg:col-span-8 md:col-span-7">
                                <div class="ltr:md:text-left rtl:md:text-right text-center relative z-1">
                                    <h3 class="text-2xl font-semibold text-black dark:text-white mb-4">Explore a job now!</h3>
                                    <p class="text-slate-400 max-w-xl">Search all the open positions on the web. Get your own personalized salary estimate. Read reviews on over 30000+ companies worldwide.</p>
                                </div>
                            </div><!--end col-->

                            <div class="lg:col-span-4 md:col-span-5">
                                <div class="ltr:text-right rtl:text-left relative z-1">
                                    <a href="employer-detail.html" class="btn bg-emerald-600 hover:bg-emerald-700 border-emerald-600 dark:border-emerald-600 text-white rounded-md">Apply Now</a>
                                    <a href="aboutus.html" class="btn bg-emerald-600/5 hover:bg-emerald-600 border-emerald-600/10 hover:border-emerald-600 text-emerald-600 hover:text-white rounded-md ms-2">Learn More</a>
                                </div>
                            </div><!--end col-->
                        </div><!--end grid-->

                        <div class="absolute -top-5 -start-5">
                            <div class="uil uil-envelope lg:text-[150px] text-7xl text-black/5 dark:text-white/5 ltr:-rotate-45 rtl:rotate-45"></div>
                        </div>

                        <div class="absolute -bottom-5 -end-5">
                            <div class="uil uil-pen lg:text-[150px] text-7xl text-black/5 dark:text-white/5 rtl:-rotate-90"></div>
                        </div>
                    </div>
                </div><!--end grid-->
            </div><!--end container-->
    </section>


    <footer class="relative bg-slate-900 dark:bg-slate-800">
        <div class="container">
            <div class="grid grid-cols-1">
                <div class="relative py-12">
                    <!-- Subscribe -->
                    <div class="relative w-full">
                        <div class="grid md:grid-cols-12 grid-cols-1 gap-[30px]">
                            <div class="md:col-span-3">
                                <a href="#" class="flex justify-center md:justify-start focus:outline-none">
                                    <img src="assets/images/logo-light.png" class="" alt="">
                                </a>
                            </div><!--end col-->

                            <div class="md:col-span-3">
                                <h4 class="md:text-xl text-xl md:leading-snug tracking-wide leading-snug font-medium text-white">About Us</h4>
                                <ul class="list-disc footer-list ltr:md:text-left rtl:md:text-left text-center space-x-3">
                                    <br>
                                    <li class="mb-1 "><a href="<?= $this->url("app", ["controller" => "application", "action" => "opportunities"]) ?>" class="text-gray-300 hover:text-gray-400 duration-500 ease-in-out font-medium">Opportunities</a></li>
                                    <li class="mb-1  mt-[10px] md:mt-0"><a href="<?= $this->url("app", ["controller" => "application", "action" => "about"]) ?>" class="text-gray-300 hover:text-gray-400 duration-500 ease-in-out font-medium">About</a></li>
                                    <li class="mb-1  mt-[10px] md:mt-0"><a href="<?= $this->url("app", ["controller" => "application", "action" => "browsejobs"]) ?>" class="text-gray-300 hover:text-gray-400 duration-500 ease-in-out font-medium">Browse Jobs</a></li>
                                    <li class=" mt-[10px] md:mt-0"><a href="<?= $this->url("app", ["controller" => "application", "action" => "terms"]) ?>" class="text-gray-300 hover:text-gray-400 duration-500 ease-in-out font-medium">Terms & Conditions</a></li>
                                    <li class=" mt-[10px] md:mt-0"><a href="<?= $this->url("app", ["controller" => "application", "action" => "privacy"]) ?>" class="text-gray-300 hover:text-gray-400 duration-500 ease-in-out font-medium">Privacy</a></li>
                                </ul><!--end icon-->
                            </div><!--end col-->

                            <div class="md:col-span-3">
                                <h4 class="md:text-xl text-xl md:leading-snug tracking-wide leading-snug font-medium text-white">Contact & Site Map</h4>
                                <ul class="list-disc footer-list ltr:md:text-left rtl:md:text-left text-center space-x-3">
                                    <br>
                                    <li class=" mt-[10px] md:mt-0"><a href="<?= $this->url("app", ["controller" => "application", "action" => "contact-us"]) ?>" class="text-gray-300 hover:text-gray-400 duration-500 ease-in-out font-medium">Contact Us</a></li>
                                    <li class=" mt-[10px] md:mt-0"><a href="<?= $this->url("app", ["controller" => "application", "action" => "companies"]) ?>" class="text-gray-300 hover:text-gray-400 duration-500 ease-in-out font-medium">Companies</a></li>
                                    <li class=" mt-[10px] md:mt-0"><a href="<?= $this->url("app", ["controller" => "application", "action" => "sitemap"]) ?>" class="text-gray-300 hover:text-gray-400 duration-500 ease-in-out font-medium">Sitemap</a></li>
                                    <li class=" mt-[10px] md:mt-0"><a href="<?= $this->url("app", ["controller" => "application", "action" => "countries"]) ?>" class="text-gray-300 hover:text-gray-400 duration-500 ease-in-out font-medium">Countries</a></li>
                                    <li class=" mt-[10px] md:mt-0"><a href="<?= $this->url("app", ["controller" => "application", "action" => "template"]) ?>" class="text-gray-300 hover:text-gray-400 duration-500 ease-in-out font-medium">Templates</a></li>
                                </ul><!--end icon-->
                            </div><!--end col-->

                            <div class="md:col-span-3">
                                <h4 class="md:text-xl text-xl md:leading-snug tracking-wide leading-snug font-medium text-white">MY ACCOUNT</h4>
                                <ul class="list-disc footer-list ltr:md:text-left rtl:md:text-left text-center space-x-3">
                                    <br>
                                    <?php if ($this->identity()) : ?>
                                        <li class=""><a href="" class="text-gray-300 hover:text-gray-400 duration-500 ease-in-out font-medium">My Account</a></li>

                                    <?php else : ?>
                                        <li class=""><a href="<?= $this->url("login") ?>" class="text-gray-300 hover:text-gray-400 duration-500 ease-in-out font-medium">Login</a></li>
                                        <li class=" mt-[10px] md:mt-0"><a href="<?= $this->url("register") ?>" class="text-gray-300 hover:text-gray-400 duration-500 ease-in-out font-medium">Register</a></li>
                                    <?php endif; ?>
                                    <li class=""><a href="<?= $this->url("app", ["controller" => "application", "action" => "recruiters-blog"]) ?>" class="text-gray-300 hover:text-gray-400 duration-500 ease-in-out font-medium">Upload CV</a></li>
                                    <li class=""><a href="<?= $this->url("app", ["controller" => "application", "action" => "recruiters-blog"]) ?>" class="text-gray-300 hover:text-gray-400 duration-500 ease-in-out font-medium">CV Builder</a></li>
                                    <li class=""><a href="<?= $this->url("app", ["controller" => "application", "action" => "advertise-job"]) ?>" class="text-gray-300 hover:text-gray-400 duration-500 ease-in-out font-medium">Advertise a job</a></li>
                                    <li class=""><a href="<?= $this->url("app", ["controller" => "application", "action" => "recruiters-blog"]) ?>" class="text-gray-300 hover:text-gray-400 duration-500 ease-in-out font-medium">Recruiters blog</a></li>

                                </ul><!--end icon-->
                            </div><!--end col-->
                        </div><!--end grid-->
                    </div>
                    <!-- Subscribe -->
                </div>
            </div>
        </div><!--end container-->

        <div class="py-[30px] px-0 border-t border-gray-800 dark:border-gray-700">
            <div class="container text-center">
                <div class="grid md:grid-cols-2 items-center gap-6">
                    <div class="ltr:md:text-left rtl:md:text-right text-center">
                        <p class="mb-0 text-gray-300 font-medium">© Design By by <a href="" target="_blank" class="text-reset"><?= GeneralService::APP_NAME ?></a>.</p>
                    </div>

                    <ul class="list-none ltr:md:text-right rtl:md:text-left text-center space-x-0.5">
                        <li class="inline"><a href="https://academy.tercesjobs.com/" target="_blank" class="btn btn-icon btn-sm border-2 border-gray-800 dark:border-gray-700 rounded-md hover:border-emerald-600 dark:hover:border-emerald-600 hover:bg-emerald-600 dark:hover:bg-emerald-600 text-white"><i class="uil uil-shopping-cart align-middle" title="Terces Academy"></i></a></li>
                        <li class="inline"><a href="https://www.tiktok.com/@tercesjobs" target="_blank" class="btn btn-icon btn-sm border-2 border-gray-800 dark:border-gray-700 rounded-md hover:border-emerald-600 dark:hover:border-emerald-600 hover:bg-emerald-600 dark:hover:bg-emerald-600 text-white"><i class="uil uil-tiktok align-middle" title="tiktok"></i></a></li>
                        <li class="inline"><a href="https://youtube.com/@tejiriemuveyan5912?si=hoHlAqrImtgXA05F" target="_blank" class="btn btn-icon btn-sm border-2 border-gray-800 dark:border-gray-700 rounded-md hover:border-emerald-600 dark:hover:border-emerald-600 hover:bg-emerald-600 dark:hover:bg-emerald-600 text-white"><i class="uil uil-youtube" title="Behance"></i></a></li>
                        <li class="inline"><a href="https://www.linkedin.com/company/tercesjobs/" target="_blank" class="btn btn-icon btn-sm border-2 border-gray-800 dark:border-gray-700 rounded-md hover:border-emerald-600 dark:hover:border-emerald-600 hover:bg-emerald-600 dark:hover:bg-emerald-600 text-white"><i class="uil uil-linkedin" title="Linkedin"></i></a></li>
                        <li class="inline"><a href="https://web.facebook.com/profile.php?id=100090477406059" target="_blank" class="btn btn-icon btn-sm border-2 border-gray-800 dark:border-gray-700 rounded-md hover:border-emerald-600 dark:hover:border-emerald-600 hover:bg-emerald-600 dark:hover:bg-emerald-600 text-white"><i class="uil uil-facebook-f align-middle" title="facebook"></i></a></li>
                        <li class="inline"><a href="https://www.instagram.com/tercesjobs/" target="_blank" class="btn btn-icon btn-sm border-2 border-gray-800 dark:border-gray-700 rounded-md hover:border-emerald-600 dark:hover:border-emerald-600 hover:bg-emerald-600 dark:hover:bg-emerald-600 text-white"><i class="uil uil-instagram align-middle" title="instagram"></i></a></li>
                        <li class="inline"><a href="https://t.me/tercesjobs" target="_blank" class="btn btn-icon btn-sm border-2 border-gray-800 dark:border-gray-700 rounded-md hover:border-emerald-600 dark:hover:border-emerald-600 hover:bg-emerald-600 dark:hover:bg-emerald-600 text-white"><i class="uil uil-telegram align-middle" title="telegram"></i></a></li>

                    </ul><!--end icon-->
                </div><!--end grid-->
            </div><!--end container-->
        </div>
    </footer><!--end footer-->

    <div class="fixed top-1/2 -right-11 z-50 hidden sm:block">
        <a href="<?= $this->url("app", ["controller" => "application", "action" => "helpdesk"]) ?>" target="_blank" class="py-1 px-3 relative inline-block rounded-t-md -rotate-90 bg-white dark:bg-slate-900 shadow-md dark:shadow dark:shadow-gray-800 font-semibold"><i class="mdi mdi-help me-1"></i> Help Desk</a>
    </div>

    <!-- JAVASCRIPTS -->

    <script src="/assets/libs/tobii/js/tobii.min.js"></script>
    <script src="/assets/libs/choices.js/public/assets/scripts/choices.min.js"></script>
    <script src="/assets/libs/tiny-slider/min/tiny-slider.js"></script>
    <script src="/assets/libs/feather-icons/feather.min.js"></script>
    <script src="/assets/js/plugins.init.js"></script>
    <script src="/assets/js/app.js"></script>
    <!-- JAVASCRIPTS -->
</body>



</html>