<?php

use General\Service\GeneralService;

?>
<?= $this->doctype() ?>
<html lang="en" class="transition-navbar-scroll top-navbar-xlarge bottom-footer" lang="en" dir="ltr">

<head>
    <meta charset="utf-8">
    <?= $this->headTitle(GeneralService::APP_NAME)->setSeparator(' - ')->setAutoEscape(false) ?>

    <!-- Font Awesome Icons -->
    <script src="https://kit.fontawesome.com/42d5adcbca.js" crossorigin="anonymous"></script>
    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?= $this->headLink([
        'rel' => 'shortcut icon',
        'type' => 'image/vnd.microsoft.icon',
        'href' => $this->basePath() . '/img/favicon.ico'
    ])

        // ->prependStylesheet("https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.2.1/flowbite.min.css")
        // ->prependStylesheet($this->basePath("assets/css/tailwind.css"))
        // ->prependStylesheet($this->basePath("assets/libs/tiny-slider/tiny-slider.css"))
        // ->prependStylesheet($this->basePath("assets/libs/@mdi/font/css/materialdesignicons.min.css"))
        // ->prependStylesheet($this->basePath("assets/libs/@iconscout/unicons/css/line.css"))
        ->prependStylesheet($this->basePath("recruiter/css/app/app.css"))
        ->prependStylesheet($this->basePath("recruiter/css/vendor/all.css"))

    ?>
    <link rel="stylesheet" href="/countryflag/country-flag.css">

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" />

    <!-- Font Awesome Link -->

    <!-- script -->



    <script src="https://unpkg.com/vue@3/dist/vue.global.js"></script>
    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

    <script src="https://cdn.jsdelivr.net/npm/vue-toast-notification@3"></script>


    <script src="https://kit.fontawesome.com/4734a25d16.js" crossorigin="anonymous"></script>
    <!-- Scripts -->

</head>

<body>



    <div class="navbar navbar-default navbar-fixed-top navbar-size-large navbar-size-xlarge paper-shadow" data-z="0" data-animated role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#main-nav">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <div class="navbar-brand navbar-brand-logo">
                    <a class="svg" href="">
                        <img src="/assets/images/logo-dark.png">
                    </a>
                </div>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="main-nav">
               <!-- <ul class="nav navbar-nav navbar-nav-margin-left">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Pages <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="index.html">Home page</a></li>
                            <li><a href="pricing.html">Pricing</a></li>
                            <li><a href="tutors.html">Tutors</a></li>
                            <li><a href="survey.html">Survey</a></li>
                            <li><a href="website-forum.html">Forum Home</a></li>
                            <li><a href="website-forum-category.html">Forum Category</a></li>
                            <li><a href="website-forum-thread.html">Forum Thread</a></li>
                            <li><a href="website-blog.html">Blog Listing</a></li>
                            <li><a href="website-blog-post.html">Blog Post</a></li>
                            <li><a href="website-contact.html">Contact</a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Courses <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="website-directory-grid.html">Grid Directory</a></li>
                            <li><a href="website-directory-list.html">List Directory</a></li>
                            <li><a href="website-course.html">Single Course</a></li>
                        </ul>
                    </li>
                    <li class="dropdown active">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Student <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li class="active"><a href="website-student-dashboard.html">Dashboard</a></li>
                            <li><a href="website-student-courses.html">My Courses</a></li>
                            <li><a href="website-take-course.html">Take Course</a></li>
                            <li><a href="website-course-forums.html">Course Forums</a></li>
                            <li><a href="website-take-quiz.html">Take Quiz</a></li>
                            <li><a href="website-student-messages.html">Messages</a></li>
                            <li><a href="website-student-profile.html">Private Profile</a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Instructor <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="website-instructor-dashboard.html">Dashboard</a></li>
                            <li><a href="website-instructor-courses.html">My Courses</a></li>
                            <li><a href="website-instructor-course-edit-course.html">Edit Course</a></li>
                            <li><a href="website-instructor-earnings.html">Earnings</a></li>
                            <li><a href="website-instructor-statement.html">Statement</a></li>
                            <li><a href="website-instructor-messages.html">Messages</a></li>
                            <li><a href="website-instructor-profile.html">Private Profile</a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">UI <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="essential-buttons.html">Buttons</a></li>
                            <li><a href="essential-icons.html">Icons</a></li>
                            <li><a href="essential-progress.html">Progress</a></li>
                            <li><a href="essential-grid.html">Grid</a></li>
                            <li><a href="essential-forms.html">Forms</a></li>
                            <li><a href="essential-tables.html">Tables</a></li>
                            <li><a href="essential-tabs.html">Tabs</a></li>
                        </ul>
                    </li>
                </ul> -->
                <div class="navbar-right">
                    <ul class="nav navbar-nav navbar-nav-bordered navbar-nav-margin-right">
                        <!-- user -->
                        <li class="dropdown user active">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <img src="/images/people/110/guy-6.jpg" alt="" class="img-circle" /><i class="fa fa-user"></i><span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu" role="menu">
                              <!--  <li class="active"><a href="website-student-dashboard.html"><i class="fa fa-bar-chart-o"></i> Dashboard</a></li>
                                <li><a href="website-student-courses.html"><i class="fa fa-mortar-board"></i> My Courses</a></li>
                                <li><a href="website-student-profile.html"><i class="fa fa-user"></i> Profile</a></li> -->
                                <li><a href="/logout"><i class="fa fa-sign-out"></i> Logout</a></li>
                            </ul>
                        </li>
                        <!-- // END user -->
                    </ul>
                    <a href="" id="location" class="navbar-btn btn btn-white ripple-dark-fade"><img :src="location"></a>
                </div>
            </div> 
            <!-- /.navbar-collapse -->

        </div>
    </div>

    <?= $this->content; ?>

    <script>
        const zoneApp = Vue.createApp({
            data() {
                return {
                    location: ""
                }
            },
            mounted() {
                this.getCustomerLocation();
            },
            methods: {
                getCustomerLocation() {

                    axios.get("https://api.ipdata.co?api-key=639fe10fc4e7a411e874c00ad8b59be1fa07f4a08e29e1f89e0c36f6").then((result) => {
                        console.log(result.data.country_code);
                        this.location = result.data.flag;
                        const parentElement = document.getElementById("flag");
                        let flag = new CountryFlag(parentElement);
                        flag.selectByAlpha2(result.data.country_code);
                    }).catch((err) => {

                    });

                }
            },
        });
        zoneApp.mount("#location");
    </script>

    <footer class="footer">
        <strong><?= GeneralService::APP_NAME; ?></strong> v1.1.0 &copy; Copyright <?= date("Y") ?>
    </footer>
    <!-- // Foot -->

    <!-- JAVASCRIPTS -->

    <script src="/recruiter/js/vendor/all.js"></script>

    <!-- Vendor Scripts Standalone Libraries -->
    <!-- <script src="js/vendor/core/all.js"></script> -->
    <!-- <script src="js/vendor/core/jquery.js"></script> -->
    <!-- <script src="js/vendor/core/bootstrap.js"></script> -->
    <!-- <script src="js/vendor/core/breakpoints.js"></script> -->
    <!-- <script src="js/vendor/core/jquery.nicescroll.js"></script> -->
    <!-- <script src="js/vendor/core/isotope.pkgd.js"></script> -->
    <!-- <script src="js/vendor/core/packery-mode.pkgd.js"></script> -->
    <!-- <script src="js/vendor/core/jquery.grid-a-licious.js"></script> -->
    <!-- <script src="js/vendor/core/jquery.cookie.js"></script> -->
    <!-- <script src="js/vendor/core/jquery-ui.custom.js"></script> -->
    <!-- <script src="js/vendor/core/jquery.hotkeys.js"></script> -->
    <!-- <script src="js/vendor/core/handlebars.js"></script> -->
    <!-- <script src="js/vendor/core/jquery.hotkeys.js"></script> -->
    <!-- <script src="js/vendor/core/load_image.js"></script> -->
    <!-- <script src="js/vendor/core/jquery.debouncedresize.js"></script> -->
    <!-- <script src="js/vendor/core/modernizr.js"></script> -->
    <!-- <script src="js/vendor/core/velocity.js"></script> -->
    <!-- <script src="js/vendor/tables/all.js"></script> -->
    <!-- <script src="js/vendor/forms/all.js"></script> -->
    <!-- <script src="js/vendor/media/slick.js"></script> -->
    <!-- <script src="js/vendor/charts/flot/all.js"></script> -->
    <!-- <script src="js/vendor/nestable/jquery.nestable.js"></script> -->
    <!-- <script src="js/vendor/countdown/all.js"></script> -->
    <!-- <script src="js/vendor/angular/all.js"></script> -->

    <!-- App Scripts Bundle
    Includes Custom Application JavaScript used for the current theme/module;
    Do not use it simultaneously with the standalone modules below. -->
    <script src="/recruiter/js/app/app.js"></script>

    <!-- App Scripts Standalone Modules
    As a convenience, we provide the entire UI framework broke down in separate modules
    Some of the standalone modules may have not been used with the current theme/module
    but ALL the modules are 100% compatible -->

    <!-- <script src="js/app/essentials.js"></script> -->
    <!-- <script src="js/app/material.js"></script> -->
    <!-- <script src="js/app/layout.js"></script> -->
    <!-- <script src="js/app/sidebar.js"></script> -->
    <!-- <script src="js/app/media.js"></script> -->
    <!-- <script src="js/app/messages.js"></script> -->
    <!-- <script src="js/app/maps.js"></script> -->
    <!-- <script src="js/app/charts.js"></script> -->

    <script src="/countryflag/country-flag.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/vue-toast-notification@3/dist/theme-sugar.css" rel="stylesheet">

    <!-- JAVASCRIPTS -->
</body>



</html>