<?php echo $this->headtitle("Aboout Us"); ?>
<!-- Start Hero -->
<section class="relative table w-full py-36 bg-[url('../../assets/images/hero/bg.jpg')] bg-top bg-no-repeat bg-cover">
    <div class="absolute inset-0 bg-emerald-900/90"></div>
    <div class="container">
        <div class="grid grid-cols-1 text-center mt-10">
            <h3 class="md:text-3xl text-2xl md:leading-snug tracking-wide leading-snug font-medium text-white">About Us</h3>

        </div><!--end grid-->
    </div><!--end container-->

    <div class="absolute text-center z-10 bottom-5 start-0 end-0 mx-3">
        <ul class="breadcrumb tracking-[0.5px] breadcrumb-light mb-0 inline-block">
            <li class="inline breadcrumb-item text-[15px] font-semibold duration-500 ease-in-out text-white/50 hover:text-white"><a href="index.html">Jobstack</a></li>
            <li class="inline breadcrumb-item text-[15px] font-semibold duration-500 ease-in-out text-white" aria-current="page">About Us</li>
        </ul>
    </div>
</section><!--end section-->
<div class="relative">
    <div class="shape absolute start-0 end-0 sm:-bottom-px -bottom-[2px] overflow-hidden z-1 text-white dark:text-slate-900">
        <svg class="w-full h-auto" viewBox="0 0 2880 48" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path d="M0 48H1437.5H2880V0H2160C1442.5 52 720 0 720 0H0V48Z" fill="currentColor"></path>
        </svg>
    </div>
</div>
<!-- End Hero -->


<section class="relative lg:py-24 py-16">
    <div class="container">
        <div class="md:flex justify-center">
            <div class="md:w-5/6">
                <div class="p-6 bg-white dark:bg-slate-900 shadow dark:shadow-gray-700 rounded-md">
                    <h5 class="text-xl font-medium mb-4">About Us :</h5>
                    <p class="text-slate-400">We are a job search platform that helps connect job seekers with the right opportunities. Our goal is to make the job search process as seamless and stress-free as possible for both job seekers and employers.</p>
                    <!--
                    <h5 class="text-xl font-medium mb-4 mt-8">User Agreements :</h5>
                    <p class="text-slate-400">The most well-known dummy text is the 'Lorem Ipsum', which is said to have <b class="text-danger-600">originated</b> in the 16th century. Lorem Ipsum is <b class="text-danger-600">composed</b> in a pseudo-Latin language which more or less <b class="text-danger-600">corresponds</b> to 'proper' Latin. It contains a series of real Latin words. This ancient dummy text is also <b class="text-danger-600">incomprehensible</b>, but it imitates the rhythm of most European languages in Latin script. The <b class="text-danger-600">advantage</b> of its Latin origin and the relative <b class="text-danger-600">meaninglessness</b> of Lorum Ipsum is that the text does not attract attention to itself or distract the viewer's <b class="text-danger-600">attention</b> from the layout.</p>
                    <p class="text-slate-400 mt-3">There is now an <b class="text-danger-600">abundance</b> of readable dummy texts. These are usually used when a text is <b class="text-danger-600">required purely</b> to fill a space. These alternatives to the classic Lorem Ipsum texts are often amusing and tell short, funny or <b class="text-danger-600">nonsensical</b> stories.</p>
                    <p class="text-slate-400 mt-3">It seems that only <b class="text-danger-600">fragments</b> of the original text remain in the Lorem Ipsum texts used today. One may speculate that over the course of time certain letters were added or deleted at various positions within the text.</p>

                    <h5 class="text-xl font-medium mb-4 mt-8">Restrictions :</h5>
                    <p class="text-slate-400">You are specifically restricted from all of the following :</p>
-->

                </div>
            </div><!--end -->
        </div><!--end grid-->
    </div><!--end container-->

    <div class="container md:mt-24 md:pb-16">
        <div class="grid md:grid-cols-12 grid-cols-1 items-center gap-[30px]">
            <div class="lg:col-span-5 md:col-span-6">
                <div class="relative">
                    <div class="relative">
                        <img src="/assets/images/about/ab01.jpg" class="lg:w-[400px] w-[280px] rounded-md shadow dark:shadow-gray-700" alt="">
                        <div class="absolute top-0 translate-y-2/4 end-0 text-center">
                           
                        </div>
                    </div>
                    <div class="absolute md:-end-5 end-0 -bottom-16">
                        <img src="/assets/images/about/ab02.jpg" class="lg:w-[280px] w-[200px] border-8 border-white dark:border-slate-900 rounded-md shadow dark:shadow-gray-700" alt="">
                    </div>
                </div>
            </div>

            <div class="lg:col-span-7 md:col-span-6 mt-14 md:mt-0">
                <div class="lg:ms-5">
                    <h3 class="mb-6 md:text-[26px] text-2xl md:leading-normal leading-normal font-semibold">As a job seeker, with access to millions of jobs. <br> Find the one that's right for you.</h3>

                    <p class="text-slate-400 max-w-xl">With Tercesjobs, you can search for jobs, upload your resume, and apply for positions all in one place. We understand that finding the right job can be overwhelming, which is why we offer a variety of tools and resources to help you in your search. From resume building tips to career advice, we have everything you need to take control of your job search and land your dream job</p>

                    <!--         <ul class="list-none text-slate-400 mt-4">
                        <li class="mb-1 flex"><i class="uil uil-check-circle text-emerald-600 text-xl me-2"></i> Digital Marketing Solutions for Tomorrow</li>
                        <li class="mb-1 flex"><i class="uil uil-check-circle text-emerald-600 text-xl me-2"></i> Our Talented & Experienced Marketing Agency</li>
                        <li class="mb-1 flex"><i class="uil uil-check-circle text-emerald-600 text-xl me-2"></i> Create your own skin to match your brand</li>
                    </ul>
-->

                </div>
            </div>
        </div><!--end grid-->
    </div><!--end container-->


    <div class="container md:mt-24 mt-16">
        <div class="grid grid-cols-1">
            <div class="relative overflow-hidden bg-emerald-600 rounded-md shadow dark:shadow-gray-700">
                <div class="grid md:grid-cols-2 items-center gap-[30px]">
                    <div class="relative">
                        <img src="/assets/images/about/ab05.jpg" alt="">
                        <div class="absolute md:bottom-1/2 md:translate-y-1/2 md:-end-10 ltr:md:translate-x-0 rtl:md:translate-x-0 -bottom-10 end-1/2 ltr:translate-x-1/2 rtl:-translate-x-1/2 text-center">
                            <!--  <a href="#!" data-type="youtube" data-id="S_CGed6E610" class="lightbox h-20 w-20 rounded-full shadow-lg dark:shadow-gray-700 inline-flex items-center justify-center bg-white dark:bg-slate-900 text-emerald-600 dark:text-white">
                              <i class="mdi mdi-play inline-flex items-center justify-center text-2xl"></i> 
                            </a>-->
                        </div>
                    </div>

                    <div>
                        <div class="text-white p-4">
                            <h4 class="leading-normal text-4xl mb-3 font-semibold">Employers<br> work efficiently</h4>

                            <p class="text-white/70 text-lg max-w-xl">As an employer or recruiter we offer you a variety of options that enable you conveniently list job opportunities and search from our vast database of potential employees to fill your recruitment needs</p>

                            <!--            <ul class="list-none text-white/50 mt-4">
                                <li class="mb-1 flex"><i class="uil uil-check-circle text-white text-xl me-2"></i> Digital Marketing Solutions for Tomorrow</li>
                                <li class="mb-1 flex"><i class="uil uil-check-circle text-white text-xl me-2"></i> Our Talented & Experienced Marketing Agency</li>
                                <li class="mb-1 flex"><i class="uil uil-check-circle text-white text-xl me-2"></i> Create your own skin to match your brand</li>
                            </ul>
-->
                        </div>
                    </div>
                </div>
            </div>
        </div><!--end grid-->
    </div><!--end container-->


</section><!--end section-->
<!-- Start -->



<section class="relative lg:py-24 py-16">

    <div class="container md:mt-24 md:pb-16">
        <div class="grid md:grid-cols-12 grid-cols-1 items-center gap-[30px]">
            <div class="lg:col-span-5 md:col-span-6">
                <div class="relative">
                    <div class="relative">
                        <img src="/assets/images/about/ab01.jpg" class="lg:w-[400px] w-[280px] rounded-md shadow dark:shadow-gray-700" alt="">
                        <div class="absolute top-0 translate-y-3/4 end-0 text-center">

                        </div>
                    </div>

                </div>
            </div>

            <div class="lg:col-span-7 md:col-span-6 mt-14 md:mt-0">
                <div class="lg:ms-5">
                    <h3 class="mb-6 md:text-[26px] text-2xl md:leading-normal leading-normal font-semibold"> CEO: </h3>

                    <p class="text-slate-400 max-w-xl">With Tercesjobs, you can search for jobs, upload your resume, and apply for positions all in one place. We understand that finding the right job can be overwhelming, which is why we offer a variety of tools and resources to help you in your search. From resume building tipsSenior Busness Consultamnt, working in Various Industries Banking , Telecommunications, Consulting and Government. She is the CEO/Founder of Tercesjobs.She has recruited over 1000 newcomers into varying positions in Canada enabling them achieve their dreams and mentored 100s of newcomers into landing a six figure tech job in Canada</p>
                    <br>
                    <p class="text-slate-400 md:mt-12 max-w-xl">She is also a tech content developer where she inspires hundreds of thousands of people in the social media space into achieving their career goals in Canada</p>
                </div>
            </div>
        </div><!--end grid-->
    </div><!--end container-->

</section>