<?php

use General\Service\GeneralService;

 echo $this->headtitle(); ?>

<!-- Start Hero -->
<section class="relative table w-full py-36 bg-[url('../../assets/images/hero/bg.jpg')] bg-top bg-no-repeat bg-cover">
    <div class="absolute inset-0 bg-emerald-900/90"></div>
    <div class="container">
        <div class="grid grid-cols-1 text-center mt-10">
            <h3 class="md:text-3xl text-2xl md:leading-snug tracking-wide leading-snug font-medium text-white">Guides & Support</h3>

        </div><!--end grid-->
    </div><!--end container-->

    <div class="absolute text-center z-10 bottom-5 start-0 end-0 mx-3">
        <ul class="breadcrumb tracking-[0.5px] breadcrumb-light mb-0 inline-block">
            <li class="inline breadcrumb-item text-[15px] font-semibold duration-500 ease-in-out text-white/50 hover:text-white"><a href="<?= $this->url("home") ?>"><?= GeneralService::APP_NAME ?></a></li>
            <li class="inline breadcrumb-item text-[15px] font-semibold duration-500 ease-in-out text-white/50 hover:text-white"><a href="<?= $this->url("home") ?>">Helpcenter</a></li>
            <li class="inline breadcrumb-item text-[15px] font-semibold duration-500 ease-in-out text-white" aria-current="page">Guides</li>
        </ul>
    </div>
</section><!--end section-->
<div class="relative">
    <div class="shape absolute start-0 end-0 sm:-bottom-px -bottom-[2px] overflow-hidden z-1 text-white dark:text-slate-900">
        <svg class="w-full h-auto" viewBox="0 0 2880 48" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path d="M0 48H1437.5H2880V0H2160C1442.5 52 720 0 720 0H0V48Z" fill="currentColor"></path>
        </svg>
    </div>
</div>
<!-- End Hero -->

<!-- Start Section-->
<section id="helper" class="relative md:py-24 py-16">
    <div class="container">
        <div class="grid lg:grid-cols-3 md:grid-cols-2 grid-cols-1 gap-[30px]">




            <div v-if="helpDeskCategory.length" v-for="(desk, index) in helpDeskCategory" class="">
                <div>
                    <h5 class="font-semibold text-xl">{{desk.category}}</h5>
                    <ul class="list-none mt-4">
                        <li v-for="help in desk.da" class="mt-2"><a href="" class="text-slate-400"><i class="mdi mdi-arrow-right text-emerald-600 me-2"></i>{{help.title}}</a></li>

                    </ul>
                </div>
            </div>


        </div><!--end grid-->
    </div><!--end container-->

    
</section><!--end section-->
<!-- End Section-->
<script>
    const helpDeskApp = Vue.createApp({
        data() {
            return {
                helpDeskCategory: [],
                helpPage: [],

            }
        },
        mounted() {
            this.getHelpCategory();
        },
        methods: {
            getHelpCategory() {
                axios.get("/apps/appsindex/web/get-help-category").then((result) => {
                    if (result.status == 200) {
                        this.helpDeskCategory = result.data.data;
                        // console.log(this.helpDeskCategory);
                        for (let i = 0; i < this.helpDeskCategory.length; i++) {
                            axios.get("/apps/appsindex/web/get-help-page/" + this.helpDeskCategory[i].uuid).then((resul) => {
                                if (resul.status == 200) {
                                    this.helpPage[i] = resul.data.data;
                                    this.helpDeskCategory[i].da = this.helpPage[i]
                                    console.log(this.helpDeskCategory);
                                }
                            }).catch((err) => {

                            });
                        }
                    }
                }).catch((err) => {

                });
            },

        },
    });
    helpDeskApp.mount("#helper")
</script>