<?php echo $this->headtitle(); ?>

<!-- Start Hero -->
<section class="relative table w-full py-36 bg-[url('../../assets/images/hero/bg.jpg')] bg-top bg-no-repeat bg-cover">
    <div class="absolute inset-0 bg-emerald-900/90"></div>
    <div class="container">
        <div class="grid grid-cols-1 text-center mt-10">
            <h3 class="md:text-3xl text-2xl md:leading-snug tracking-wide leading-snug font-medium text-white">Guides & Support</h3>

        </div><!--end grid-->
    </div><!--end container-->

    <div class="absolute text-center z-10 bottom-5 start-0 end-0 mx-3">
        <ul class="breadcrumb tracking-[0.5px] breadcrumb-light mb-0 inline-block">
            <li class="inline breadcrumb-item text-[15px] font-semibold duration-500 ease-in-out text-white/50 hover:text-white"><a href="index.html">Jobstack</a></li>
            <li class="inline breadcrumb-item text-[15px] font-semibold duration-500 ease-in-out text-white/50 hover:text-white"><a href="helpcenter-overview.html">Helpcenter</a></li>
            <li class="inline breadcrumb-item text-[15px] font-semibold duration-500 ease-in-out text-white" aria-current="page">Guides</li>
        </ul>
    </div>
</section><!--end section-->
<div class="relative">
    <div class="shape absolute start-0 end-0 sm:-bottom-px -bottom-[2px] overflow-hidden z-1 text-white dark:text-slate-900">
        <svg class="w-full h-auto" viewBox="0 0 2880 48" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path d="M0 48H1437.5H2880V0H2160C1442.5 52 720 0 720 0H0V48Z" fill="currentColor"></path>
        </svg>
    </div>
</div>
<!-- End Hero -->

<!-- Start Section-->
<section class="relative md:py-24 py-16">
    <div class="container">
        <div class="grid lg:grid-cols-3 md:grid-cols-2 grid-cols-1 gap-[30px]">
            <div class="">
                <h5 class="font-semibold text-xl">Getting started</h5>
                <ul class="list-none mt-4">
                    <li class="mt-2"><a href="" class="text-slate-400"><i class="mdi mdi-arrow-right text-emerald-600 me-2"></i>Deciding to purchase</a></li>
                    <li class="mt-2"><a href="" class="text-slate-400"><i class="mdi mdi-arrow-right text-emerald-600 me-2"></i>List your space</a></li>
                    <li class="mt-2"><a href="" class="text-slate-400"><i class="mdi mdi-arrow-right text-emerald-600 me-2"></i>Landing an experience or adventure</a></li>
                    <li class="mt-2"><a href="" class="text-slate-400"><i class="mdi mdi-arrow-right text-emerald-600 me-2"></i>Top uses questions</a></li>
                </ul>
            </div>

            <div class="">
                <h5 class="font-semibold text-xl">Your calendar</h5>
                <ul class="list-none mt-4">
                    <li class="mt-2"><a href="" class="text-slate-400"><i class="mdi mdi-arrow-right text-emerald-600 me-2"></i>Pricing & availability</a></li>
                    <li class="mt-2"><a href="" class="text-slate-400"><i class="mdi mdi-arrow-right text-emerald-600 me-2"></i>Booking settings</a></li>
                    <li class="mt-2"><a href="" class="text-slate-400"><i class="mdi mdi-arrow-right text-emerald-600 me-2"></i>Responding to enquiries & requests</a></li>
                    <li class="mt-2"><a href="" class="text-slate-400"><i class="mdi mdi-arrow-right text-emerald-600 me-2"></i>Snoozing or deactivating your listing</a></li>
                </ul>
            </div>

            <div class="">
                <h5 class="font-semibold text-xl">Your listings</h5>
                <ul class="list-none mt-4">
                    <li class="mt-2"><a href="" class="text-slate-400"><i class="mdi mdi-arrow-right text-emerald-600 me-2"></i>Updating your listing</a></li>
                    <li class="mt-2"><a href="" class="text-slate-400"><i class="mdi mdi-arrow-right text-emerald-600 me-2"></i>Neighbourhoods</a></li>
                    <li class="mt-2"><a href="" class="text-slate-400"><i class="mdi mdi-arrow-right text-emerald-600 me-2"></i>Listing photos & photography</a></li>
                    <li class="mt-2"><a href="" class="text-slate-400"><i class="mdi mdi-arrow-right text-emerald-600 me-2"></i>Jobstack Plus</a></li>
                    <li class="mt-2"><a href="" class="text-slate-400"><i class="mdi mdi-arrow-right text-emerald-600 me-2"></i>API-connected software</a></li>
                </ul>
            </div>

            <div class="">
                <h5 class="font-semibold text-xl">How payouts work</h5>
                <ul class="list-none mt-4">
                    <li class="mt-2"><a href="" class="text-slate-400"><i class="mdi mdi-arrow-right text-emerald-600 me-2"></i>Getting paid</a></li>
                    <li class="mt-2"><a href="" class="text-slate-400"><i class="mdi mdi-arrow-right text-emerald-600 me-2"></i>Adding payout info</a></li>
                    <li class="mt-2"><a href="" class="text-slate-400"><i class="mdi mdi-arrow-right text-emerald-600 me-2"></i>Your payout status</a></li>
                    <li class="mt-2"><a href="" class="text-slate-400"><i class="mdi mdi-arrow-right text-emerald-600 me-2"></i>Donations</a></li>
                    <li class="mt-2"><a href="" class="text-slate-400"><i class="mdi mdi-arrow-right text-emerald-600 me-2"></i>Taxes</a></li>
                </ul>
            </div>

            <div class="">
                <h5 class="font-semibold text-xl">Your reservations</h5>
                <ul class="list-none mt-4">
                    <li class="mt-2"><a href="" class="text-slate-400"><i class="mdi mdi-arrow-right text-emerald-600 me-2"></i>Jobstack safely</a></li>
                    <li class="mt-2"><a href="" class="text-slate-400"><i class="mdi mdi-arrow-right text-emerald-600 me-2"></i>Jobstack Experiences and Adventures</a></li>
                    <li class="mt-2"><a href="" class="text-slate-400"><i class="mdi mdi-arrow-right text-emerald-600 me-2"></i>Changing a reservation</a></li>
                    <li class="mt-2"><a href="" class="text-slate-400"><i class="mdi mdi-arrow-right text-emerald-600 me-2"></i>Cancelling a reservation</a></li>
                    <li class="mt-2"><a href="" class="text-slate-400"><i class="mdi mdi-arrow-right text-emerald-600 me-2"></i>Long-term reservations</a></li>
                </ul>
            </div>

            <div class="">
                <h5 class="font-semibold text-xl">Reservation help</h5>
                <ul class="list-none mt-4">
                    <li class="mt-2"><a href="" class="text-slate-400"><i class="mdi mdi-arrow-right text-emerald-600 me-2"></i>Help with a reservation or guest</a></li>
                    <li class="mt-2"><a href="" class="text-slate-400"><i class="mdi mdi-arrow-right text-emerald-600 me-2"></i>Guest cancellations</a></li>
                </ul>
            </div>

            <div class="">
                <h5 class="font-semibold text-xl">Your account</h5>
                <ul class="list-none mt-4">
                    <li class="mt-2"><a href="" class="text-slate-400"><i class="mdi mdi-arrow-right text-emerald-600 me-2"></i>Your profile</a></li>
                    <li class="mt-2"><a href="" class="text-slate-400"><i class="mdi mdi-arrow-right text-emerald-600 me-2"></i>Account security</a></li>
                    <li class="mt-2"><a href="" class="text-slate-400"><i class="mdi mdi-arrow-right text-emerald-600 me-2"></i>Identification & verifications</a></li>
                    <li class="mt-2"><a href="" class="text-slate-400"><i class="mdi mdi-arrow-right text-emerald-600 me-2"></i>Reviews</a></li>
                    <li class="mt-2"><a href="" class="text-slate-400"><i class="mdi mdi-arrow-right text-emerald-600 me-2"></i>Superhost status</a></li>
                </ul>
            </div>
        </div><!--end grid-->
    </div><!--end container-->

    <div class="container-fluid md:mt-24 mt-16">
        <div class="container">
            <div class="grid grid-cols-1">
                <div class="relative overflow-hidden lg:px-8 px-6 py-10 rounded-xl shadow-lg dark:shadow-gray-700">
                    <div class="grid md:grid-cols-12 grid-cols-1 items-center gap-[30px]">
                        <div class="lg:col-span-8 md:col-span-7">
                            <div class="ltr:md:text-left rtl:md:text-right text-center relative z-1">
                                <h3 class="text-2xl font-semibold text-black dark:text-white mb-4">Explore a job now!</h3>
                                <p class="text-slate-400 max-w-xl">Search all the open positions on the web. Get your own personalized salary estimate. Read reviews on over 30000+ companies worldwide.</p>
                            </div>
                        </div>

                        <div class="lg:col-span-4 md:col-span-5">
                            <div class="ltr:text-right rtl:text-left relative z-1">
                                <a href="employer-detail.html" class="btn bg-emerald-600 hover:bg-emerald-700 border-emerald-600 dark:border-emerald-600 text-white rounded-md">Apply Now</a>
                                <a href="aboutus.html" class="btn bg-emerald-600/5 hover:bg-emerald-600 border-emerald-600/10 hover:border-emerald-600 text-emerald-600 hover:text-white rounded-md ms-2">Learn More</a>
                            </div>
                        </div>
                    </div>

                    <div class="absolute -top-5 -start-5">
                        <div class="uil uil-envelope lg:text-[150px] text-7xl text-black/5 dark:text-white/5 ltr:-rotate-45 rtl:rotate-45"></div>
                    </div>

                    <div class="absolute -bottom-5 -end-5">
                        <div class="uil uil-pen lg:text-[150px] text-7xl text-black/5 dark:text-white/5 rtl:-rotate-90"></div>
                    </div>
                </div>
            </div><!--end grid-->
        </div><!--end container-->
    </div><!--end container-->
</section><!--end section-->
<!-- End Section-->
<script>
    const helpDeskApp = Vue.createApp({
        data() {
            return {
                helpDeskCategory: [],
            }
        },
        methods: {
            getHelpCategory() {
                axios.get("").then((result) => {
                    if(result.status == 200){
                        
                    }
                }).catch((err) => {

                });
            }
        },
    })
</script>