<?php

/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>

<!-- Start Hero -->
<section class="relative md:py-56 py-36 w-full">
    <div class="absolute inset-0 bg-emerald-600/5 dark:bg-emerald-600/10"></div>
    <div class="container z-1">
        <div class="grid grid-cols-1 text-center mt-10 relative">
            <h4 class="lg:leading-normal leading-normal text-4xl lg:text-5xl mb-5 font-bold">Join us & <span class="text-emerald-600 font-bold">Explore</span> <br> <span class="text-emerald-600 font-bold">Thousands</span> of Jobs</h4>
            <p class="text-slate-400 text-lg max-w-xl mx-auto">Find Jobs, Employment & Career Opportunities. Some of the companies we've helped recruit excellent applicants over the years.</p>

            <div class="d-flex" id="reserve-form">
                <div class="md:w-5/6 mx-auto">
                    <div class="lg:col-span-10 mt-8">
                        <div class="bg-white dark:bg-slate-900 border-0 shadow rounded-md p-3">
                            <form action="#">
                                <div class="registration-form text-dark text-start">
                                    <div class="grid lg:grid-cols-4 md:grid-cols-2 grid-cols-1 lg:gap-0 gap-6">
                                        <div class="filter-search-form relative filter-border">
                                            <i class="uil uil-briefcase-alt icons"></i>
                                            <input name="name" type="text" id="job-keyword" class="form-input filter-input-box bg-gray-50 dark:bg-slate-800 border-0" placeholder="Search your Keywords">
                                        </div>

                                        <div class="filter-search-form relative filter-border">
                                            <i class="uil uil-map-marker icons"></i>
                                            <select class="form-select" data-trigger name="choices-location" id="choices-location" aria-label="Default select example">
                                                <option value="AF">Afghanistan</option>
                                                <option value="AZ">Azerbaijan</option>
                                                <option value="BS">Bahamas</option>
                                                <option value="BH">Bahrain</option>
                                                <option value="CA">Canada</option>
                                                <option value="CV">Cape Verde</option>
                                                <option value="DK">Denmark</option>
                                                <option value="DJ">Djibouti</option>
                                                <option value="ER">Eritrea</option>
                                                <option value="EE">Estonia</option>
                                                <option value="GM">Gambia</option>
                                            </select>
                                        </div>

                                        <div class="filter-search-form relative filter-border">
                                            <i class="uil uil-briefcase-alt icons"></i>
                                            <select class="form-select" data-trigger name="choices-type" id="choices-type" aria-label="Default select example">
                                                <option selected="" value="1">Full Time</option>
                                                <option value="2">Part Time</option>
                                                <option value="3">Freelancer</option>
                                                <option value="4">Remote Work</option>
                                                <option value="5">Office Work</option>
                                            </select>
                                        </div>

                                        <input type="submit" id="search" name="search" style="height: 60px;" class="btn bg-emerald-600 hover:bg-emerald-700 border-emerald-600 hover:border-emerald-700 text-white searchbtn submit-btn w-100" value="Search">
                                    </div><!--end grid-->
                                </div><!--end container-->
                            </form>
                        </div>
                    </div><!--ed col-->
                </div>
            </div><!--end grid-->

            <div class="mt-4">
                <span class="text-slate-400"><span class="text-dark">Popular Searches :</span> Designer, Developer, Web, IOS, PHP Senior Engineer</span>
            </div>

            <div class="absolute -top-20 start-1/2 -translate-x-1/2">
                <div class="w-10 h-10 animate-[bounce_2s_infinite] bg-white dark:bg-slate-900 flex items-center justify-center shadow dark:shadow-gray-700 rounded-md">
                    <img src="assets/images/company/facebook-logo.png" class="h-6 w-6" alt="">
                </div>
            </div>

            <div class="absolute top-[20%] start-10">
                <div class="w-10 h-10 animate-[spin_5s_linear_infinite] bg-white dark:bg-slate-900 flex items-center justify-center shadow dark:shadow-gray-700 rounded-md">
                    <img src="assets/images/company/google-logo.png" class="h-6 w-6" alt="">
                </div>
            </div>

            <div class="absolute top-[20%] end-1">
                <div class="w-10 h-10 bg-white dark:bg-slate-900 flex items-center justify-center shadow dark:shadow-gray-700 rounded-md">
                    <img src="assets/images/company/android.png" class="h-6 w-6" alt="">
                </div>
            </div>

            <div class="absolute top-3/4 start-1">
                <div class="w-10 h-10 bg-white dark:bg-slate-900 flex items-center justify-center shadow dark:shadow-gray-700 rounded-md">
                    <img src="assets/images/company/lenovo-logo.png" class="h-6 w-6" alt="">
                </div>
            </div>

            <div class="absolute top-3/4 end-10">
                <div class="w-10 h-10 animate-[spin_5s_linear_infinite] bg-white dark:bg-slate-900 flex items-center justify-center shadow dark:shadow-gray-700 rounded-md">
                    <img src="assets/images/company/skype.png" class="h-6 w-6" alt="">
                </div>
            </div>

            <div class="absolute -bottom-32 start-1/2 -translate-x-1/2">
                <div class="w-10 h-10 animate-pulse bg-white dark:bg-slate-900 flex items-center justify-center shadow dark:shadow-gray-700 rounded-md">
                    <img src="assets/images/company/snapchat.png" class="h-6 w-6" alt="">
                </div>
            </div>
        </div><!--end grid-->
    </div><!--end container-->

    

    <div class="container md:mt-24 mt-16">
        <div class="grid grid-cols-1 pb-8 text-center">
            <h3 class="mb-4 md:text-[26px] md:leading-normal text-2xl leading-normal font-semibold">Popular Jobs</h3>

            <p class="text-slate-400 max-w-xl mx-auto">Search all the open positions on the web. Get your own personalized salary estimate. Read reviews on over 30000+ companies worldwide.</p>
        </div><!--end grid-->

        <div class="grid grid-cols-1 mt-8 gap-[30px]">
            <div class="group relative overflow-hidden md:flex justify-between items-center rounded shadow hover:shadow-md dark:shadow-gray-700 transition-all duration-500 p-5">
                <div class="flex items-center">
                    <div class="w-14 h-14 flex items-center justify-center bg-white dark:bg-slate-900 shadow dark:shadow-gray-700 rounded-md">
                        <img src="assets/images/company/facebook-logo.png" class="h-8 w-8" alt="">
                    </div>
                    <a href="job-detail-one.html" class="text-lg hover:text-emerald-600 font-semibold transition-all duration-500 ms-3 min-w-[180px]">Web Designer</a>
                </div>

                <div class="md:block flex justify-between md:mt-0 mt-4">
                    <span class="block"><span class="bg-emerald-600/10 inline-block text-emerald-600 text-xs px-2.5 py-0.5 font-semibold rounded-full">Full Time</span></span>
                    <span class="block text-slate-400 text-sm md:mt-1 mt-0"><i class="uil uil-clock"></i> 20th Feb 2023</span>
                </div>

                <div class="md:block flex justify-between md:mt-0 mt-2">
                    <span class="text-slate-400"><i class="uil uil-map-marker"></i> Australia</span>
                    <span class="block font-semibold md:mt-1 mt-0">$4,000 - $4,500</span>
                </div>

                <div class="md:mt-0 mt-4">
                    <a href="" class="btn btn-icon rounded-full bg-emerald-600/5 hover:bg-emerald-600 border-emerald-600/10 hover:border-emerald-600 text-emerald-600 hover:text-white md:relative absolute top-0 end-0 md:m-0 m-3"><i data-feather="bookmark" class="h-4 w-4"></i></a>
                    <a href="job-apply.html" class="btn rounded-md bg-emerald-600 hover:bg-emerald-700 border-emerald-600 hover:border-emerald-700 text-white md:ms-2 w-full md:w-auto">Apply Now</a>
                </div>

                <span class="w-24 bg-yellow-400 text-white text-center absolute ltr:-rotate-45 rtl:rotate-45 -start-[30px] top-1"><i class="uil uil-star"></i></span>
            </div><!--end content-->

            <div class="group relative overflow-hidden md:flex justify-between items-center rounded shadow hover:shadow-md dark:shadow-gray-700 transition-all duration-500 p-5">
                <div class="flex items-center">
                    <div class="w-14 h-14 flex items-center justify-center bg-white dark:bg-slate-900 shadow dark:shadow-gray-700 rounded-md">
                        <img src="assets/images/company/google-logo.png" class="h-8 w-8" alt="">
                    </div>
                    <a href="job-detail-one.html" class="text-lg hover:text-emerald-600 font-semibold transition-all duration-500 ms-3 min-w-[180px]">Marketing Director</a>
                </div>

                <div class="md:block flex justify-between md:mt-0 mt-4">
                    <span class="block"><span class="bg-emerald-600/10 inline-block text-emerald-600 text-xs px-2.5 py-0.5 font-semibold rounded-full">Part Time</span></span>
                    <span class="block text-slate-400 text-sm md:mt-1 mt-0"><i class="uil uil-clock"></i> 20th Feb 2023</span>
                </div>

                <div class="md:block flex justify-between md:mt-0 mt-2">
                    <span class="text-slate-400"><i class="uil uil-map-marker"></i> USA</span>
                    <span class="block font-semibold md:mt-1 mt-0">$4,000 - $4,500</span>
                </div>

                <div class="md:mt-0 mt-4">
                    <a href="" class="btn btn-icon rounded-full bg-emerald-600/5 hover:bg-emerald-600 border-emerald-600/10 hover:border-emerald-600 text-emerald-600 hover:text-white md:relative absolute top-0 end-0 md:m-0 m-3"><i data-feather="bookmark" class="h-4 w-4"></i></a>
                    <a href="job-apply.html" class="btn rounded-md bg-emerald-600 hover:bg-emerald-700 border-emerald-600 hover:border-emerald-700 text-white md:ms-2 w-full md:w-auto">Apply Now</a>
                </div>
            </div><!--end content-->

            <div class="group relative overflow-hidden md:flex justify-between items-center rounded shadow hover:shadow-md dark:shadow-gray-700 transition-all duration-500 p-5">
                <div class="flex items-center">
                    <div class="w-14 h-14 flex items-center justify-center bg-white dark:bg-slate-900 shadow dark:shadow-gray-700 rounded-md">
                        <img src="assets/images/company/android.png" class="h-8 w-8" alt="">
                    </div>
                    <a href="job-detail-one.html" class="text-lg hover:text-emerald-600 font-semibold transition-all duration-500 ms-3 min-w-[180px]">App Developer</a>
                </div>

                <div class="md:block flex justify-between md:mt-0 mt-4">
                    <span class="block"><span class="bg-emerald-600/10 inline-block text-emerald-600 text-xs px-2.5 py-0.5 font-semibold rounded-full">Remote</span></span>
                    <span class="block text-slate-400 text-sm md:mt-1 mt-0"><i class="uil uil-clock"></i> 20th Feb 2023</span>
                </div>

                <div class="md:block flex justify-between md:mt-0 mt-2">
                    <span class="text-slate-400"><i class="uil uil-map-marker"></i> China</span>
                    <span class="block font-semibold md:mt-1 mt-0">$4,000 - $4,500</span>
                </div>

                <div class="md:mt-0 mt-4">
                    <a href="" class="btn btn-icon rounded-full bg-emerald-600/5 hover:bg-emerald-600 border-emerald-600/10 hover:border-emerald-600 text-emerald-600 hover:text-white md:relative absolute top-0 end-0 md:m-0 m-3"><i data-feather="bookmark" class="h-4 w-4"></i></a>
                    <a href="job-apply.html" class="btn rounded-md bg-emerald-600 hover:bg-emerald-700 border-emerald-600 hover:border-emerald-700 text-white md:ms-2 w-full md:w-auto">Apply Now</a>
                </div>
            </div><!--end content-->

            <div class="group relative overflow-hidden md:flex justify-between items-center rounded shadow hover:shadow-md dark:shadow-gray-700 transition-all duration-500 p-5">
                <div class="flex items-center">
                    <div class="w-14 h-14 flex items-center justify-center bg-white dark:bg-slate-900 shadow dark:shadow-gray-700 rounded-md">
                        <img src="assets/images/company/lenovo-logo.png" class="h-8 w-8" alt="">
                    </div>
                    <a href="job-detail-one.html" class="text-lg hover:text-emerald-600 font-semibold transition-all duration-500 ms-3 min-w-[180px]">Product Designer</a>
                </div>

                <div class="md:block flex justify-between md:mt-0 mt-4">
                    <span class="block"><span class="bg-emerald-600/10 inline-block text-emerald-600 text-xs px-2.5 py-0.5 font-semibold rounded-full">WFH</span></span>
                    <span class="block text-slate-400 text-sm md:mt-1 mt-0"><i class="uil uil-clock"></i> 20th Feb 2023</span>
                </div>

                <div class="md:block flex justify-between md:mt-0 mt-2">
                    <span class="text-slate-400"><i class="uil uil-map-marker"></i> Dubai</span>
                    <span class="block font-semibold md:mt-1 mt-0">$4,000 - $4,500</span>
                </div>

                <div class="md:mt-0 mt-4">
                    <a href="" class="btn btn-icon rounded-full bg-emerald-600/5 hover:bg-emerald-600 border-emerald-600/10 hover:border-emerald-600 text-emerald-600 hover:text-white md:relative absolute top-0 end-0 md:m-0 m-3"><i data-feather="bookmark" class="h-4 w-4"></i></a>
                    <a href="job-apply.html" class="btn rounded-md bg-emerald-600 hover:bg-emerald-700 border-emerald-600 hover:border-emerald-700 text-white md:ms-2 w-full md:w-auto">Apply Now</a>
                </div>
            </div><!--end content-->

            <div class="group relative overflow-hidden md:flex justify-between items-center rounded shadow hover:shadow-md dark:shadow-gray-700 transition-all duration-500 p-5">
                <div class="flex items-center">
                    <div class="w-14 h-14 flex items-center justify-center bg-white dark:bg-slate-900 shadow dark:shadow-gray-700 rounded-md">
                        <img src="assets/images/company/spotify.png" class="h-8 w-8" alt="">
                    </div>
                    <a href="job-detail-one.html" class="text-lg hover:text-emerald-600 font-semibold transition-all duration-500 ms-3 min-w-[180px]">C++ Developer</a>
                </div>

                <div class="md:block flex justify-between md:mt-0 mt-4">
                    <span class="block"><span class="bg-emerald-600/10 inline-block text-emerald-600 text-xs px-2.5 py-0.5 font-semibold rounded-full">Full Time</span></span>
                    <span class="block text-slate-400 text-sm md:mt-1 mt-0"><i class="uil uil-clock"></i> 20th Feb 2023</span>
                </div>

                <div class="md:block flex justify-between md:mt-0 mt-2">
                    <span class="text-slate-400"><i class="uil uil-map-marker"></i> India</span>
                    <span class="block font-semibold md:mt-1 mt-0">$4,000 - $4,500</span>
                </div>

                <div class="md:mt-0 mt-4">
                    <a href="" class="btn btn-icon rounded-full bg-emerald-600/5 hover:bg-emerald-600 border-emerald-600/10 hover:border-emerald-600 text-emerald-600 hover:text-white md:relative absolute top-0 end-0 md:m-0 m-3"><i data-feather="bookmark" class="h-4 w-4"></i></a>
                    <a href="job-apply.html" class="btn rounded-md bg-emerald-600 hover:bg-emerald-700 border-emerald-600 hover:border-emerald-700 text-white md:ms-2 w-full md:w-auto">Apply Now</a>
                </div>

                <span class="w-24 bg-yellow-400 text-white text-center absolute ltr:-rotate-45 rtl:rotate-45 -start-[30px] top-1"><i class="uil uil-star"></i></span>
            </div><!--end content-->

            <div class="group relative overflow-hidden md:flex justify-between items-center rounded shadow hover:shadow-md dark:shadow-gray-700 transition-all duration-500 p-5">
                <div class="flex items-center">
                    <div class="w-14 h-14 flex items-center justify-center bg-white dark:bg-slate-900 shadow dark:shadow-gray-700 rounded-md">
                        <img src="assets/images/company/linkedin.png" class="h-8 w-8" alt="">
                    </div>
                    <a href="job-detail-one.html" class="text-lg hover:text-emerald-600 font-semibold transition-all duration-500 ms-3 min-w-[180px]">Php Developer</a>
                </div>

                <div class="md:block flex justify-between md:mt-0 mt-4">
                    <span class="block"><span class="bg-emerald-600/10 inline-block text-emerald-600 text-xs px-2.5 py-0.5 font-semibold rounded-full">Remote</span></span>
                    <span class="block text-slate-400 text-sm md:mt-1 mt-0"><i class="uil uil-clock"></i> 20th Feb 2023</span>
                </div>

                <div class="md:block flex justify-between md:mt-0 mt-2">
                    <span class="text-slate-400"><i class="uil uil-map-marker"></i> Pakistan</span>
                    <span class="block font-semibold md:mt-1 mt-0">$4,000 - $4,500</span>
                </div>

                <div class="md:mt-0 mt-4">
                    <a href="" class="btn btn-icon rounded-full bg-emerald-600/5 hover:bg-emerald-600 border-emerald-600/10 hover:border-emerald-600 text-emerald-600 hover:text-white md:relative absolute top-0 end-0 md:m-0 m-3"><i data-feather="bookmark" class="h-4 w-4"></i></a>
                    <a href="job-apply.html" class="btn rounded-md bg-emerald-600 hover:bg-emerald-700 border-emerald-600 hover:border-emerald-700 text-white md:ms-2 w-full md:w-auto">Apply Now</a>
                </div>

                <span class="w-24 bg-yellow-400 text-white text-center absolute ltr:-rotate-45 rtl:rotate-45 -start-[30px] top-1"><i class="uil uil-star"></i></span>
            </div><!--end content-->
        </div><!--end grid-->

        <div class="grid md:grid-cols-1 grid-cols-1 mt-8">
            <div class="md:col-span-12 text-center">
                <a href="job-grid-two.html" class="btn btn-link text-slate-400 hover:text-emerald-600 after:bg-emerald-600 duration-500 ease-in-out">See More Jobs <i class="uil uil-arrow-right align-middle"></i></a>
            </div>
        </div><!--end grid-->
    </div><!--end container-->
</section><!--end section-->
<!-- End Hero -->
<?php //echo $this->partial("application/terces/academy"); 
?>

<script>
    const homeApp = Vue.createApp({
        data() {
            return {
                latestJobs: [],
            }
        },
        methods: {
            getLatestJobs() {
                axios.get("").then((result) => {
                    if (result.status == 200) {
                        this.latestJobs = result.data.data;
                    }
                }).catch((err) => {

                });

            }
        },
    })
</script>